import React, { createContext, useState, useContext, useEffect, useCallback } from 'react';

const LanguageContext = createContext();

// Translations for different languages
const translations = {
  en: {
    // General terms
    welcome: "Welcome",
    student: "Student",
    parent: "Parent",
    admin: "Admin",
    teacher: "Teacher",
    teacherDashboard: "Teacher Dashboard",
    logout: "Logout",
    home: "Home",
    dashboard: "Dashboard",
    profile: "Profile",
    support: "Support",
    uploadProfilePicture: "Upload Profile Picture",
    grades: "Grades",
    notifications: "Notifications",
    analytics: "Analytics",
    courses: "Courses",
    gpa: "GPA",
    credits: "Credits",
    courseCode: "Course Code",
    courseName: "Course Name",
    myAssignments: "My Assignments",
    messages: "Messages",
    analytics: "System Analytics",
    enhancedAnalytics: "Enhanced Visual Analytics",
    manageStudents: "Manage Students",
    gradeApprovals: "Grade Approvals",
    examApprovals: "Exam Approvals",
    reportCardGen: "Report Card Gen",
    createOnlineExam: "Create Online Exam",
    editProfile: "Edit Profile",
    semester: "Semester",
    grade: "Grade",
    score: "Score",
    status: "Status",
    published: "Published",
    login: "Login",
    register: "Register",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm Password",
    fullName: "Full Name",
    studentId: "Student ID",
    phone: "Phone",
    department: "Department",
    year: "Year",
    relationship: "Relationship",
    yourName: "Your Name",
    yourEmail: "Your Email",
    yourPhone: "Your Phone",
    childStudentId: "Child's Student ID",
    approve: "Approve",
    reject: "Reject",
    actions: "Actions",
    approveLink: "Approve Link",
    rejectLink: "Reject Link",
    pending: "Pending",
    approved: "Approved",
    rejected: "Rejected",
    active: "Active",
    newNotification: "NEW",
    parentAccess: "Parent Access",
    passedCourses: "Passed Courses",
    totalCredits: "Total Credits",
    coursesTaken: "Courses Taken",
    academicRecord: "Academic Record",
    currentGPA: "Current GPA",
    welcomeMessage: "Welcome, {name}!",
    studentIdLabel: "Student ID: {id}",
    computerScience: "Computer Science",
    yearNumber: "Year {year}",
    selectLanguage: "Select Language",
    english: "English",
    amharic: "አማርኛ",
    oromo: "Oromoo",
    somali: "Somali",
    contactAdvisor: "Contact Advisor",
    downloadReport: "Download Report",
    academicPerformance: "Academic Performance",
    autoUpdated: "Auto-Updated",
    alertsNotifications: "Alerts & Notifications",
    academicProgress: "Academic Progress",
    academicAdvisory: "Academic Status Advisory",
    academicAdvisoryMessage: "Critical Alert: Our records show you have received one or more low grades (D or F). To continue your studies at the university, you must maintain a satisfactory GPA. Please focus on your upcoming assessments and consult with your academic advisor if you need support.",
    advisor: "Advisor",
    subject: "Subject",
    yourMessage: "Your Message",
    writeMessagePlaceholder: "Write your message here...",
    cancel: "Cancel",
    sendMessage: "Send Message",
    regardingAcademicProgress: "Regarding {studentName}'s Academic Progress",
    loginFailedMessage: "Login failed. Please check your credentials.",
    universityGradePortal: "University Grade Portal",
    transparentAcademicMonitoring: "Secure academic progress tracking with appropriate access controls",
    selectYourRole: "Select Your Role",
    studentLogin: "Student Login",
    parentLogin: "Parent Login",
    adminLogin: "Admin Login",
    viewGradesAndAcademicProgress: "View your grades and academic progress",
    monitorChildAcademicPerformance: "Monitor your child's academic performance",
    uploadAndManageStudentGrades: "Upload and manage student grades",
    teacherLogin: "Teacher Login",
    uploadGradesByYearAndSemester: "Upload grades by year and semester",
    recentUploads: "Recent Uploads",
    adminReviewRequired: "Admin Review Required",
    academicYear: "Academic Year",
    demo: "Demo",
    loginAs: "Login as",
    demoApplication: "Demo Application",
    demoApplicationDescription: "This system provides secure access to academic records with appropriate permissions. Enter your credentials and click login.",
    newUserRegisterFirst: "New user? Register first",
    registerAsStudent: "Register as Student",
    registerAsParent: "Register as Parent",
    enterYourEmail: "Enter your email",
    enterYourPassword: "Enter your password",
    fullNameRequired: "Full name is required",
    studentIdRequired: "Student ID is required",
    emailRequired: "Email is required",
    validEmailRequired: "Valid email is required",
    passwordLengthRequired: "Password must be at least 8 characters",
    passwordsDoNotMatch: "Passwords do not match",
    phoneRequired: "Phone number is required",
    agreeToTermsRequired: "You must agree to terms",
    studentAlreadyExists: "Student with this ID or email already exists",
    studentRegistrationSuccess: "Student registration successful! You can now login.",
    studentRegistration: "Student Registration",
    registerAsStudentToAccessPortal: "Register as a student to access your academic portal",
    fullNamePlaceholder: "Abebe Kebede",
    studentIdPlaceholder: "UGR/1234/14",
    emailPlaceholder: "student@example.com",
    passwordPlaceholder: "At least 8 characters",
    confirmPasswordPlaceholder: "Confirm your password",
    phonePlaceholder: "+251 911 223344",
    teacherRegistration: "Teacher Registration",
    registerAsTeacher: "Register as Teacher",
    registerAsTeacherToAccessPortal: "Complete your teacher account registration to access the teaching portal",
    teacherIdLabel: "Teacher ID: {id}",
    teacherIdRequired: "Teacher ID is required",
    teacherIdPlaceholder: "e.g. T1001",
    registerAsTeacherSuccess: "Your teacher registration has been submitted successfully.",
    teacherRegistrationError: "An error occurred during teacher registration.",
    selectDepartment: "Select Department",
    year1: "Year 1",
    year2: "Year 2",
    year3: "Year 3",
    year4: "Year 4",
    year5: "Year 5",
    agreeToShareAcademicInfo: "I agree to share my academic information with registered parents/guardians and receive notifications about my academic progress",
    alreadyHaveAccount: "Already have an account?",
    loginHere: "Login here",
    parents: "Parents:",
    electricalEngineering: "Electrical Engineering",
    mechanicalEngineering: "Mechanical Engineering",
    civilEngineering: "Civil Engineering",
    medicine: "Medicine",
    businessAdministration: "Business Administration",
    law: "Law",
    agriculture: "Agriculture",
    father: "Father",
    mother: "Mother",
    guardian: "Guardian",
    otherRelative: "Other Relative",
    parentRegistration: "Parent Registration",
    registerAsParentToMonitorAcademicProgress: "Register as a parent to monitor your child's academic progress",
    yourFullName: "Your Full Name",
    yourEmailOptional: "Your Email (Optional)",
    verify: "Verify",
    studentVerified: "✓ Student Verified",
    relationshipToStudent: "Relationship to Student",
    parentConfirmationMessage: "I confirm that I am the parent/guardian of the student mentioned above and agree to receive notifications about their academic progress",
    parentRegistrationSuccessWithEmail: "Parent registration successful! Waiting for admin approval. You will receive email/SMS when approved.",
    parentRegistrationSuccessWithoutEmail: "Parent registration successful! Waiting for admin approval. You will receive SMS notifications when approved.",
    parentAlreadyRegistered: "Parent with this email or relationship already registered for this student",
    studentNotFoundMessage: "Student not found. Student must register first.",
    settings: "Settings",
    changePassword: "Change Password",
    updateProfile: "Update Profile",
    adminDashboard: "Admin Dashboard",
    totalStudents: "Total Students",
    totalParents: "Total Parents",
    totalGrades: "Total Grades",
    pendingRequests: "Pending Requests",
    quickActions: "Quick Actions",
    uploadGrades: "Upload Grades",
    manageLinkRequests: "Manage Link Requests",
    recentGrades: "Recent Grades",
    noRecentGrades: "No recent grades",
    welcomeBack: "Welcome back",
    saveChanges: "Save Changes",
    currentPassword: "Current Password",
    newPassword: "New Password",
    profileUpdatedSuccessfully: "Profile updated successfully",
    passwordChangedSuccessfully: "Password changed successfully",
    errorUpdatingProfile: "Error updating profile",
    errorChangingPassword: "Error changing password",
    profile: "Profile",
    exportTranscript: "Export Transcript",
    printTranscript: "Print Transcript",
    filterGrades: "Filter Grades",
    clearFilters: "Clear Filters",
    pleaseEnterAllFields: "Please enter all fields",
    loginSuccessful: "Login successful!",
    loggingIn: "Logging in",
    relationshipRequired: "Relationship is required",
    selectRelationship: "Select Relationship",
    verifyStudentIdFirst: "Please verify student ID first",
    validEmailRequiredOrLeaveEmpty: "Please enter a valid email address or leave empty",
    students: "Students:",
    studentManagement: "Student Management",
    manageStudentInformation: "Manage student information, update details, and maintain academic records",
    confirmDeleteStudent: "Are you sure you want to delete this student? This action cannot be undone.",
    studentUpdatedSuccessfully: "Student updated successfully!",
    errorUpdatingStudent: "Error updating student",
    errorDeletingStudent: "Error deleting student",
    studentDeletedSuccessfully: "Student deleted successfully!",
    name: "Name",
    save: "Save",
    edit: "Edit",
    delete: "Delete",
    messageToParent: "Message to Parent",
    notificationTitle: "Notification Title",
    actionIssueDescription: "Action/Issue Description",
    sendNotification: "Send Notification",
    directChat: 'Direct Chat',
    nationalId: 'National ID (Fayda)',
    scanQRToRegister: 'Scan QR to Register',
    quickRegistration: 'Quick Registration',
    idVerified: 'ID Verified',
    idPending: 'ID Pending Verification',
    notificationSentSuccessfully: "Notification Sent Successfully",
    studentIssueReport: "Student Issue Report",
    administrativeAction: "Administrative Action",
    regulationProblem: "Regulation Problem",
    unregulatedAction: "Unregulated Action/Problem",
    notLinkedToParent: "Not Linked to Parent",
    linkedToParent: "Linked to Parent ({name})",
    searchByIdOrName: "Search by Student ID or Name...",
    attendance: "Attendance",
    attendanceRate: "Attendance Rate",
    attendanceHistory: "Attendance History",
    totalSessions: "Total Sessions",
    present: "Present",
    absent: "Absent",
    late: "Late",
    excused: "Excused",
    remarks: "Remarks",
    date: "Date",
    loadingDashboard: "Loading dashboard...",
    loading: "Loading...",
    myAttendance: "My Attendance",
    gradesWillAppearHere: "Grades will appear here once they are uploaded.",
    noNotifications: "No notifications at this time.",
    viewAnalytics: "View Analytics",
    manageAttendance: "Manage Attendance",
    selectAll: "Select All",
    deselectAll: "Deselect All",
    remove: "Remove",
    selected: "Selected",
    confirmRemoveSelected: "Remove {count} selected grade(s) from recent grades display?",
    confirmRemoveAll: "Remove all {count} recent grades from display?",
    successfullyRemoved: "Successfully removed {count} grade(s) from recent display.",
    noGradesSelected: "No grades selected to remove.",
    failedToRemove: "Failed to remove grades. Please try again.",
    lowGpaWarning: "Critical Notice: Your child's current academic performance has fallen below the university's recommended standard (GPA {gpa}). To ensure they can successfully continue their studies, immediate focus on upcoming assessments is required. We recommend discussing this with the student and potentially contacting their academic advisor.",
    messageSentToAdvisor: "Message sent to {advisor}!",
    viewMyGrades: "View My Grades",
    viewChildGrades: "View Child Grades",
    linkNewStudent: "Link New Student",
    sendAnnouncement: "Send Announcement",
    attendanceRecord: "Attendance Record",
    loadingGrades: "Loading grades...",
    noGradesYet: "No Grades Yet",
    noGradesYetMessage: "Your grades will appear here once they are uploaded by your instructor.",
    currentSemester: "Current Semester",
    detailedGradeView: "Detailed view of all grades",
    noGradesFound: "No Grades Found",
    noGradesRecordedMessage: "There are no grades recorded for this student yet.",
    creditHours: "Credit Hours",
    referenceAllYears: "Reference All Years",
    noStudentsFound: "No students found matching your criteria.",
    sending: "Sending...",
    type: "Type",
    excellent: "Excellent",
    viewPresenceRecords: "View your presence records for all courses.",
    noAttendanceRecords: "No attendance records found.",
    noNotificationsTitle: "No Notifications",
    noNotificationsMessage: "You don't have any notifications at this time.",
    notification: "Notification",
    markAsRead: "Mark as read",
    approveSuccess: "Parent linked to student successfully! Notification sent.",
    rejectSuccess: "Link request rejected.",
    // Admin Announcements
    broadcastNotification: "Broadcast a real-time notification to students and parents.",
    announcementSentSuccess: "Announcement sent successfully!",
    failedToSendAnnouncement: "Failed to send announcement.",
    fillTitleMessage: "Please fill in both title and message.",
    announcementPlaceholderTitle: "e.g. Exam Schedule Released",
    announcementPlaceholderMessage: "Write your announcement here...",
    targetAudience: "Target Audience",
    everyone: "Everyone (Students & Parents)",
    allStudents: "All Students",
    allParents: "All Parents",
    filterByYear: "Filter by Year (Students)",
    // Admin Upload
    gradeManagementPortal: "Grade Management Portal",
    gradeManagementDescription: "Upload and manage student grades. Parents receive automatic notifications when grades are published.",
    notificationsSent: "Notifications Sent",
    bulkUpload: "Bulk Upload",
    selectFile: "Select CSV or Excel File",
    csvExcelOnly: "CSV or Excel files only",
    fileSize: "File Size",
    uploadProcessFile: "Upload & Process File",
    addSingleGrade: "Add Single Grade",
    scoreOptional: "Score (Optional)",
    addGradeRecord: "Add Grade Record",
    gradeRecords: "Grade Records",
    publishAllPending: "Publish All Pending",
    studentsByYear: "Students by Year",
    showAllGrades: "Show All Grades",
    noStudentsForYear: "No students found for selected year.",
    notificationStatus: "Notification",
    sent: "Sent",
    // Analytics
    noAnalyticsData: "No analytics data available",
    ensureGradesUploaded: "Please ensure grades have been uploaded.",
    academicAnalytics: "University-Wide Academic Analytics",
    analyticsDescription: "Comprehensive overview of university performance, department trends, and at-risk students.",
    universityAvgGPA: "University Avg GPA",
    enrolledStudents: "Enrolled Students",
    totalGradesRecorded: "Total Grades Recorded",
    studentsAtRisk: "Students At Risk",
    performanceByDepartment: "Performance by Department",
    avgGPA: "Avg GPA",
    generalGradeDistribution: "General Grade Distribution",
    atRiskStudentsTitle: "⚠️ At-Risk Students (GPA < 2.0 or Failing Grades)",
    studentsFlagged: "Students Flagged",
    issue: "Issue",
    action: "Action",
    hasFailedCourses: "Has Failed Course(s)",
    lowAcademicStanding: "Low Academic Standing",
    notifyParent: "Notify Parent",
    noAtRiskStudents: "No students currently at risk. Good job!",
    // Reports
    academicReports: "Academic Reports & Transcripts",
    reportsDescription: "Generate and download comprehensive academic reports",
    exportCSV: "Export CSV",
    print: "Print",
    fullTranscript: "Full Transcript",
    semesterReport: "Semester Report",
    summaryReport: "Summary Report",
    courseGrades: "Course Grades",
    officialTranscript: "Official Academic Transcript",
    dateGenerated: "Date Generated",
    overallGPA: "Overall GPA",
    academicSummary: "Academic Summary",
    totalCourses: "Total Courses",
    exportedToCSV: "Report exported to CSV",
    // Settings
    passwordChangedSuccessfully: "Password changed successfully",
    errorChangingPassword: "Error changing password",
    // Alerts
    academicAlertsTitle: "Academic Alerts & Warnings",
    alertsDescription: "Stay informed about your child's academic performance",
    alertMarkedAsRead: "Alert marked as read",
    errorMarkingAlert: "Error marking alert as read",
    allAlertsMarkedAsRead: "All alerts marked as read",
    errorMarkingAllAlerts: "Error marking alerts as read",
    allAlerts: "All Alerts",
    unread: "Unread",
    critical: "Critical",
    highPriority: "High Priority",
    noAlerts: "No Alerts",
    allAlertsRead: "All alerts have been read",
    noCriticalAlerts: "No critical alerts",
    noAlertsToDisplay: "No alerts to display",
    courseLabel: "Course",
    newBadge: "NEW",
    // Link Student
    linkAnotherStudent: "Link Another Student",
    linkStudentDescription: "Add another child to your account to monitor their progress.",
    enterStudentId: "Enter Student ID (e.g., S12345)",
    submitting: "Submitting...",
    requestLink: "Request Link",
    linkAlreadyExists: "This student ID is already linked to a family account. Only one parent account can be linked to a student.",
    studentIdNotFound: "Student ID not found.",
    errorVerifyingStudent: "Error verifying student ID.",
    // Registration Hints
    passwordRequirements: "Password must contain at least 1 letter, 1 number, and 1 special character.",
    emailSavePrompt: "Your login email: {email} \n\nPlease save this email for future logins!",
    emailUniqueHint: "Must be unique if provided. Leave blank to auto-generate.",
    passwordHint: "Must include at least 1 letter, 1 number, 1 special character (@$!%*#?&), minimum 6 characters.",
    phoneHint: "Must be unique. Used for SMS status updates.",
    studentIdHint: "Enter your official university student ID (e.g., UGR/1234/14).",
    fullNameHint: "Enter your full legal name as it appears on official documents.",
    emailHint: "Enter a valid email address (e.g., student@university.edu).",
    confirmPasswordHint: "Re-enter the same password as above to confirm.",
    phoneFormatHint: "Enter a valid phone number (e.g., +251-911-234-567).",
    // Grade Details
    gradeDetailsTitle: "Grade Details",
    gradeNotFound: "Grade Not Found",
    gradeNotFoundMessage: "The requested grade could not be found.",
    goBack: "Go Back",
    studentInformation: "Student Information",
    studentName: "Student Name",
    letterGrade: "Letter Grade",
    scoreLabel: "Score",
    gradePoint: "Grade Point",
    performanceScore: "Performance Score",
    uploadedDate: "Uploaded Date",
    uploadedBy: "Uploaded By",
    parentsNotified: "Parents Notified",
    yes: "Yes",
    no: "No",
    performanceEvaluation: "Performance Evaluation",
    percentage: "Percentage",
    scoreRatio: "Score Ratio",
    gpaContribution: "GPA Contribution",
    printReport: "Print Report",
    backToGrades: "Back to Grades",
    // Attendance Management
    attendanceManagementTitle: "Attendance Management",
    selectStudent: "Select Student",
    recordAttendance: "Record Attendance",
    attendanceRecordedSuccess: "Attendance recorded successfully!",
    errorRecordingAttendance: "Error recording attendance",
    // New Features
    auditLogs: "Audit Logs",
    academicCalendar: "Academic Calendar",
    courseResources: "Course Resources",
    feeManagement: "Fee Management",
    library: "Library",
    idCard: "ID Card",
    gradeAppeals: "Grade Appeals",
    calendar: "Calendar",
    resources: "Resources",
    fees: "Fees",
    schedule: "Schedule",
    notificationPreference: "Notification Preference",
    receiveNotificationsVia: "How would you like to receive notifications?",
    emailOnly: "Email Only",
    smsOnly: "SMS (Phone) Only",
    bothEmailAndSms: "Both Email & SMS",
    onlineExams: "Online Exams",
    startExam: "Start Exam",
    next: "Next",
    back: "Back",
    submitExam: "Submit Exam",
    timeLeft: "Time Left",
    question: "Question",
    submitExam: "Submit Exam",
    timeLeft: "Time Left",
    question: "Question",
    finalSubmit: "Final Submit",
    completeYourProfile: "Complete Your Profile",
    completeProfileDescription: "Please set your Department, Year, and Semester to continue.",
    saveAndContinue: "Save & Continue",
    fillTitleMessageOrAttachment: "Please fill in title AND provide a message OR attachment.",
    attachment: "Attachment",
    addAdmin: "Add Admin",
    manageRecentGrades: "Manage the latest grade submissions",
    errorLoadingDashboard: "Error Loading Dashboard",
    retry: "Retry",
    addAdministrator: "Add Administrator",
    addNewAdministrator: "Add New Administrator",
    grantAdminAccess: "Grant administrative access to a new user",
    createAdminAccount: "Create Admin Account",
    addingAdministrator: "Adding Administrator...",
    securityNote: "Security Note",
    adminSecurityWarning: "This new administrator will have full access to manage students, grades, and system settings. Ensure you are granting access to an authorized person.",
    generalAdministration: "General Administration",
    itDepartment: "IT Department",
    academicRegistry: "Academic Registry",
    financeOffice: "Finance Office",
    studentAffairs: "Student Affairs",
    adminAddedSuccess: "New administrator successfully added!",
    failedToAddAdmin: "Failed to add administrator",
    confirmRemoveGrades: "Remove {count} selected grade(s) from recent grades display?",
    confirmRemoveAllGrades: "Remove all recent grades from display?",
    noGradesSelectedToRemove: "No grades selected to remove.",
    passwordsDoNotMatch: "Passwords do not match",
    fullNamePlaceholder: "Enter full name"
  },
  // Amharic translations
  am: {
    welcome: "እናመሰግናለን",
    student: "ተማሪ",
    parent: "ወላጅ",
    admin: "አስተዳደር",
    teacher: "አስተማሪ",
    teacherDashboard: "የአስተማሪ ዳሽቦርድ",
    logout: "መውጣት",
    home: "መነሻ",
    dashboard: "ዳሽቦርድ",
    profile: "መገለጫ",
    support: "ድጋፍ",
    uploadProfilePicture: "የመገለጫ ምስል ይስቀሉ",
    completeYourProfile: "መገለጫዎን ያጠናቁ",
    completeProfileDescription: "እባክዎን ከቀጠለዎት ክፍልዎን ፣ ዓመትዎን እና ሴሚስተርዎን ያስተካክሉ።",
    saveAndContinue: "አስቀምጥ እና ቀጥል",
    fillTitleMessageOrAttachment: "እባክዎ ርዕሱን ይሙሉ እና መልእክት ወይም አባሪ ያቅርቡ።",
    attachment: "አባሪ",
    grades: "ደረጃዎች",
    notifications: "ማሳወቂያዎች",
    analytics: "ትንታኔ",
    courses: "ትምህርቶች",
    gpa: "GPA",
    credits: "ክሬዲቶች",
    courseCode: "የትምህርት ኮድ",
    courseName: "የትምህርት ስም",
    myAssignments: "የእኔ ተግባራት",
    messages: "መልዕክቶች",
    analytics: "የስርዓት ትንታኔ",
    enhancedAnalytics: "የላቀ ምስል ትንታኔ",
    manageStudents: "ተማሪዎችን ያስተዳድሩ",
    gradeApprovals: "የውጤት ማረጋገጫዎች",
    examApprovals: "የፈተና ማረጋገጫዎች",
    reportCardGen: "የሪፖርት ካርድ ዝግጅት",
    createOnlineExam: "የመስመር ላይ ፈተና ይፍጠሩ",
    editProfile: "መገለጫ አዘምን",
    semester: "ሰሜስተር",
    grade: "ደረጃ",
    score: "ነጥብ",
    status: "ሁኔታ",
    published: "ታተመ",
    login: "ግባ",
    register: "ተመዝገብ",
    email: "ኢሜይል",
    password: "የይለፍ ቃል",
    confirmPassword: "የይለፍ ቃል ያረጋግጡ",
    fullName: "ሙሉ ስም",
    studentId: "የተማሪ መለያ",
    phone: "ስልክ",
    department: "የትምህርት ቤት",
    year: "ዓመት",
    relationship: "ግንኙነት",
    yourName: "የእርስዎ ስም",
    yourEmail: "የእርስዎ ኢሜይል",
    yourPhone: "የእርስዎ ስልክ",
    childStudentId: "የልጅዎ መለያ ቁጥር",
    approve: "አንቀሳቅስ",
    reject: "አስተካክል",
    actions: "እርምጃዎች",
    approveLink: "አገናኝ አንቀሳቅስ",
    rejectLink: "አገናኝ አስተካክል",
    pending: "በመጠባበቅ ላይ",
    approved: "ተቀድቷል",
    rejected: "ተቀባይነት አላገኘም",
    active: "ንቁ",
    newNotification: "አዲስ",
    parentAccess: "የወላጅ መዳረሻ",
    passedCourses: "ተጠናቋ የሆኑ ትምህርቶች",
    totalCredits: "ጠቅላላ ክሬዲቶች",
    coursesTaken: "ተጠናቋ የሆኑ ትምህርቶች",
    academicRecord: "የትምህርት መዝገብ",
    currentGPA: "የአሁኑ GPA",
    welcomeMessage: "እናመሰግናለን, {name}!",
    studentIdLabel: "የተማሪ መለያ: {id}",
    computerScience: "የኮምፒውተር ሳይንስ",
    yearNumber: "ዓመት {year}",
    selectLanguage: "ቋንቋ ይምረጡ",
    english: "እንግሊዝኛ",
    amharic: "አማርኛ",
    oromo: "ኦሮሞኛ",
    somali: "ሱማልኛ",
    tigrinya: "ትግርኛ",
    contactAdvisor: "የክል አድቫይዘር",
    downloadReport: "ሪፖርት ማውረድ",
    academicPerformance: "አካዳሚክ አፈጻጸም",
    autoUpdated: "ራስ-ሰር የተዘመነ",
    alertsNotifications: "ማሳወቂያዎች",
    academicProgress: "የትምህርት እድገት",
    academicAdvisory: "የትምህርት ሁኔታ ምክር",
    academicAdvisoryMessage: "ወሳኝ ማስጠንቀቂያ፡- መረጃዎቻችን እንደሚያሳዩት አንድ ወይም ከዚያ በላይ ዝቅተኛ ውጤቶችን (D ወይም F) አግኝተዋል። በዩኒቨርሲቲው ትምህርትዎን ለመቀጠል፣ አጥጋቢ GPA መያዝ አለብዎት። እባክዎን በሚቀጥሉት ምዘናዎችዎ ላይ ያተኩሩ እና ድጋፍ ካስፈለገዎት ከአካዳሚክ አማካሪዎ ጋር ይማከሩ።",
    advisor: "አድቫይዘር",
    subject: "ርዕስ",
    yourMessage: "የእርስዎ መልዕክት",
    writeMessagePlaceholder: "መልዕክትዎን እዚህ ይፃፉ...",
    cancel: "ሰርዝ",
    sendMessage: "መልዕክት ላክ",
    regardingAcademicProgress: "{studentName} የትምህርት እድገት ስለ",
    loginFailedMessage: "ግባቱ አልተሳካም። እባክዎ ማረጋገጫዎችዎን ይመርምሩ.",
    universityGradePortal: "የዩኒቨርሲቲ ዲግሪ ፖርታል",
    transparentAcademicMonitoring: "አርታዒ የትምህርት እድገት መከታተያ በተንባይ የመዳረሻ ቁጥጥሮች ውስጥ",
    selectYourRole: "የእርስዎን ሚና ይምረጡ",
    studentLogin: "የተማሪ ግቢ",
    parentLogin: "የወላጅ ግቢ",
    adminLogin: "የአስተዳደር ግቢ",
    viewGradesAndAcademicProgress: "የእርስዎን ደረጃዎች እና አካዳሚክ እድገት ይመልከቱ",
    monitorChildAcademicPerformance: "የልጅዎን አካዳሚክ አፈፃፅም ይከታተሉ",
    uploadAndManageStudentGrades: "የተማሪ ደረጃዎችን ይጫኑ እና ያስተዳድሩ",
    teacherLogin: "የአስተማሪ ግቢ",
    uploadGradesByYearAndSemester: "ደረጃዎችን በዓመት እና በሰሚስተር ይጫኑ",
    recentUploads: "የቅርብ ጊዜ ሰቀላዎች",
    adminReviewRequired: "የአስተዳዳሪ ግምገማ ያስፈልጋል",
    academicYear: "የትምህርት ዘመን",
    demo: "ዲሞንስትራሽን",
    loginAs: "እንደ ይግቡ",
    demoApplication: "የዲሞንስትራሽን መተግበሪያ",
    demoApplicationDescription: "ይህ ስርዓት በተንባይ ፈቃዶች ውስጥ የትምህርት መረጃዎችን ለመዳረስ ያስችልዎታል። ማረጋገጫዎችዎን ያስገቡ እና ግባ ይጫኑ።",
    newUserRegisterFirst: "አዲስ ተጠቃሚ? በመጀመሪያ ይመዝገቡ",
    registerAsStudent: "እንደ ተማሪ ይመዝገቡ",
    enterYourEmail: "ኢሜይልዎን ያስገቡ",
    enterYourPassword: "የይለፍ ቃልዎን ያስገቡ",
    fullNameRequired: "ሙሉ ስም ያስፈልገዋል",
    studentIdRequired: "የተማሪ መለያ ያስፈልገዋል",
    emailRequired: "ኢሜይል ያስፈልገዋል",
    validEmailRequired: "ዋጋዊ ኢሜይል ያስፈልገዋል",
    passwordLengthRequired: "የይለፍ ቃሉ ቢያንስ 6 ባህሪ መሆን አለበት",
    passwordsDoNotMatch: "የይለፍ ቃላቱ አይዛመዱም",
    phoneRequired: "ስልክ ቁጥር ያስፈልገዋል",
    agreeToTermsRequired: "ውሎችን መስማት አለብዎት",
    studentAlreadyExists: "ለዚህ መለያ ወይም ኢሜይል ተማሪ አስቀድሞ አለ",
    studentRegistrationSuccess: "የተማሪ ምዝገባ ተሳክቷል! እንደገና መግባት ይችላሉ.",
    studentRegistration: "የተማሪ ምዝገባ",
    registerAsStudentToAccessPortal: "ለተማሪ ፖርታልዎ መግባት እንደ ተማሪ ይመዝገቡ",
    fullNamePlaceholder: "አበበ ቀበዴ",
    studentIdPlaceholder: "ዩጂአር/1234/14",
    emailPlaceholder: "ተማሪ@ለምሳሌ.com",
    passwordPlaceholder: "ቢያንስ 6 ባህሪዎች",
    confirmPasswordPlaceholder: "የይለፍ ቃሉን ያረጋግጡ",
    phonePlaceholder: "+251 911 223344",
    teacherRegistration: "የአስተማሪ ምዝገባ",
    registerAsTeacher: "እንደ አስተማሪ ይመዝገቡ",
    registerAsTeacherToAccessPortal: "የትምህርት መግቢያ በርን ለመጠቀም የአስተማሪ መለያዎን ምዝገባ ያጠናቁ",
    teacherIdRequired: "የአስተማሪ መለያ ያስፈልገዋል",
    teacherIdPlaceholder: "ለምሳሌ፦ T1001",
    registerAsTeacherSuccess: "የአስተማሪ ምዝገባዎ በተሳካ ሁኔታ ቀርቧል።",
    teacherRegistrationError: "በአስተማሪ ምዝገባ ወቅት ስህተት ተከስቷል።",
    selectDepartment: "የትምህርት ቤት ይምረጡ",
    year1: "ዓመት 1",
    year2: "ዓመት 2",
    year3: "ዓመት 3",
    year4: "ዓመት 4",
    year5: "ዓመት 5",
    agreeToShareAcademicInfo: "ለተመዘገቡ ወላጆች/እናቶች የአካዳሚክ መረጃዬን ለማጋራት እና ስለ አካዳሚክ ውጤቴ ማሳወቂያዎችን ለማግኘት እስማማለሁ",
    alreadyHaveAccount: "መለያ ቁጥር አለዎት?",
    loginHere: "እዚህ ይግቡ",
    parents: "ወላጆች:",
    electricalEngineering: "ኤሌክትሪክ ምህንድስና",
    mechanicalEngineering: "ሜካኒካል ምህንድስና",
    civilEngineering: "ሲቪል ምህንድስና",
    medicine: "ሕክምና",
    businessAdministration: "ንግድ አስተዳደር",
    law: "ሕግ",
    agriculture: "እርሻ",
    father: "አባት",
    mother: "እናት",
    guardian: "አስተዳዳሪ",
    otherRelative: "ሌላ ጠባይ",
    parentRegistration: "የወላጅ ምዝገባ",
    registerAsParentToMonitorAcademicProgress: "የልጅዎን አካዳሚክ ውጤት ለመከታተል እንደ ወላጅ ይመዝገቡ",
    yourFullName: "የእርስዎ ሙሉ ስም",
    yourEmailOptional: "የእርስዎ ኢሜይል (አማራጭ)",
    verify: "ማረጋገጫ",
    studentVerified: "✓ ተማሪ ተረጋግጧል",
    relationshipToStudent: "ወደ ተማሪ",
    parentConfirmationMessage: "ላይ የተጠቀሰው ተማሪ ወላጅ/አስተዳዳሪ እኔ መሆንኝን እና ስለ አካዳሚክ ውጤቱ ማሳወቂያዎችን ለማግኘት እስማማለሁ",
    parentRegistrationSuccessWithEmail: "የወላጅ ምዝገባ ተሳክቷል! አስተዳደር ፍቃድ ለመስጠት በመጠባበቅ ላይ። ፍቃድ ከተሰጠ በኋላ ኢሜይል/ኤስኤምኤስ ይደርሳል።",
    parentRegistrationSuccessWithoutEmail: "የወላጅ ምዝገባ ተሳክቷል! አስተዳደር ፍቃድ ለመስጠት በመጠባበቅ ላይ። ፍቃድ ከተሰጠ በኋላ ኤስኤምኤስ ማሳወቂያዎች ይደርሳል።",
    parentAlreadyRegistered: "ለዚህ ተማሪ ወላጅ አስቀድሞ ተመዝግቧል",
    studentNotFoundMessage: "ተማሪ አልተገኘም። ተማሪ በመጀመሪያ መዝገብ አለበት።",
    verifyStudentIdFirst: "የተማሪ መለያ ቁጥር በመጀመሪያ ያረጋግጡ",
    validEmailRequiredOrLeaveEmpty: "ዋጋዊ ኢሜይል ያስገቡ ወይም ባዶ ይተው",
    students: "ተማሪዎች:",
    studentManagement: "የተማሪ አስተዳደር",
    manageStudentInformation: "የተማሪ መረጃ አስተዳደር፣ ዝርዝሮችን ያዘምኑ እና የትምህርት መዝገቦችን ያስተናግሩ",
    confirmDeleteStudent: "ይህን ተማሪ ለማጥፋት እርግጠኛ ነዎት? ይህ ተግባር ሊቀለበስ አይችልም።",
    studentUpdatedSuccessfully: "ተማሪ በተሳካ ሁኔታ ዘምኗል!",
    errorUpdatingStudent: "የተማሪን መረጃ ማዘመን ሲሳካ",
    errorDeletingStudent: "ተማሪን ማጥፋት ሲሳካ",
    studentDeletedSuccessfully: "ተማሪ በተሳካ ሁኔታ ተወግድኗል!",
    name: "ስም",
    save: "አስቀምጥ",
    edit: "አርትዕ",
    delete: "አጥፋ",
    notifyParent: "ወላጅን አሳውቅ",
    messageToParent: "ለወላጅ የሚላክ መልዕክት",
    notificationTitle: "የማሳወቂያ ርዕስ",
    actionIssueDescription: "የድርጊት/ጉዳይ መግለጫ",
    sendNotification: "ማሳወቂያ ላክ",
    directChat: 'ቀጥታ ውይይት',
    nationalId: 'ብሔራዊ መታወቂያ (ፋይዳ)',
    scanQRToRegister: 'ለመመዝገብ QR ይቃኙ',
    quickRegistration: 'ፈጣን ምዝገባ',
    idVerified: 'መታወቂያ ተረጋግጧል',
    idPending: 'መታወቂያ ማረጋገጫ በመጠባበቅ ላይ',
    notificationSentSuccessfully: "ማሳወቂያ በተሳካ ሁኔታ ተልኳል",
    studentIssueReport: "የተማሪ ችግር ሪፖርት",
    administrativeAction: "የአስተዳደር እርምጃ",
    regulationProblem: "የစည်းክብር ችግር",
    unregulatedAction: "ያልተስተካከለ ድርጊት/ችግር",
    notLinkedToParent: "ከወላጅ ጋር አልተገናኘም",
    linkedToParent: "ከወላጅ ጋር ተገናኝቷል ({name})",
    searchByIdOrName: "በተማሪ መለያ ወይም ስም ይፈልጉ...",
    attendance: "መገኘት",
    attendanceRate: "የመገኘት መጠን",
    attendanceHistory: "የመገኘት ታሪክ",
    totalSessions: "ጠቅላላ ክፍለ ጊዜያት",
    present: "ተገኝቷል",
    absent: "ቀርቷል",
    late: "ዘግይቷል",
    excused: "ይቅርታ የተደረገለት",
    remarks: "አስተያየቶች",
    date: "ቀን",
    loadingDashboard: "ዳሽቦርድ በመጫን ላይ...",
    loading: "በመጫን ላይ...",
    myAttendance: "የእኔ መገኘት",
    noGradesAvailable: "ምንም ደረጃዎች የሉም",
    gradesWillAppearHere: "ደረጃዎች ሲጫኑ እዚህ ይታያሉ።",
    noNotifications: "በአሁኑ ጊዜ ምንም ማሳወቂያዎች የሉም።",
    viewAnalytics: "ትንታኔዎችን ይመልከቱ",
    manageAttendance: "መገኘትን ያስተዳድሩ",
    selectAll: "ሁሉንም ይምረጡ",
    deselectAll: "ሁሉንም አታንሱ",
    remove: "አስወግድ",
    selected: "የተመረጡ",
    confirmRemoveSelected: "የተመረጡትን {count} ደረጃዎች ከቅርብ ጊዜ ደረጃዎች ማሳያ ያስወግዱ?",
    confirmRemoveAll: "ሁሉንም {count} የቅርብ ጊዜ ደረጃዎች ከማሳያ ያስወግዱ?",
    successfullyRemoved: "{count} ደረጃዎች በተሳካ ሁኔታ ከቅርብ ጊዜ ማሳያ ተወግዳሉ።",
    noGradesSelected: "ለማስወገድ የተመረጡ ምንም ደረጃዎች የሉም።",
    failedToRemove: "ደረጃዎችን ማስወገድ አልተሳካም። እባክዎ እንደገና ይሞክሩ።",
    lowGpaWarning: "ወሳኝ ማስጠንቀቂያ፡ የልጅዎ የአሁን አካዳሚክ አፈጻጸም ከዩኒቨርሲቲው ምክረ ሃሳብ በታች ወድቋል (GPA {gpa})። ትምህርታቸውን በተሳካ ሁኔታ መቀጠል እንዲችሉ፣ በሚመጡት ፈተናዎች ላይ አፋጣኝ ትኩረት ያስፈልጋል። ይህንን ከተማሪው ጋር እንዲወያዩ እና ከአካዳሚክ አማካሪው ጋር እንዲገናኙ እንመክራለን።",
    messageSentToAdvisor: "መልዕክት ለ {advisor} ተልኳል!",
    welcomeBack: "እንኳን በደህና መጡ",
    adminDashboard: "የአስተዳደር ዳሽቦርድ",
    viewMyGrades: "ውጤቶቼን ይመልከቱ",
    viewChildGrades: "የልጅ ውጤቶችን ይመልከቱ",
    linkNewStudent: "አዲስ ተማሪ ያገናኙ",
    sendAnnouncement: "ማስታወቂያ ላክ",
    manageLinkRequests: "የግንኙነት ጥያቄዎችን ያስተዳድሩ",
    uploadGrades: "ውጤቶችን ይጫኑ",
    attendanceRecord: "የመገኘት መዝገብ",
    recentGrades: "የቅርብ ጊዜ ውጤቶች",
    noRecentGrades: "ምንም የቅርብ ጊዜ ውጤቶች የሉም",
    department: "የትምህርት ክፍል",
    currentGPA: "የአሁኑ GPA",
    year: "ዓመት",
    academicAdvisory: "የአካዳሚክ ምክር",
    regardingAcademicProgress: "ስለ {studentName} አካዳሚክ አፈጻጸም",
    subject: "ርዕሰ ጉዳይ",
    yourMessage: "የእርስዎ መልእክት",
    cancel: "ሰርዝ",
    sendMessage: "መልእክት ላክ",
    advisor: "አማካሪ",
    email: "ኢሜይል",
    student: "ተማሪ",
    pending: "በመጠባበቅ ላይ",
    loadingGrades: "ውጤቶችን በመጫን ላይ...",
    noGradesYet: "ምንም ውጤቶች የሉም",
    noGradesYetMessage: "ውጤቶችዎ በአስተማሪዎ ከተጫኑ በኋላ እዚህ ይታያሉ።",
    currentSemester: "የአሁኑ ሴሚስተር",
    detailedGradeView: "የሁሉም ውጤቶች ዝርዝር እይታ",
    noGradesFound: "ምንም ውጤቶች አልተገኙም",
    noGradesRecordedMessage: "ለዚህ ተማሪ እስካሁን የተመዘገበ ውጤት የለም።",
    creditHours: "የክሬዲት ሰዓቶች",
    referenceAllYears: "ሁሉንም ዓመታት ዋቢ ያድርጉ",
    noStudentsFound: "ከፍለጋዎ ጋር የሚዛመዱ ተማሪዎች አልተገኙም።",
    sending: "በመላክ ላይ...",
    type: "ዓይነት",
    excellent: "በጣም ጥሩ",
    viewPresenceRecords: "ለሁሉም ኮርሶች የመገኘት መዝገቦችን ይመልከቱ",
    noAttendanceRecords: "ምንም የመገኘት መዝገብ አልተገኘም",
    noNotificationsTitle: "ምንም ማሳወቂያዎች የሉም",
    noNotificationsMessage: "በአሁኑ ጊዜ ምንም ማሳወቂያዎች የለዎትም",
    notification: "ማሳወቂያ",
    markAsRead: "እንደተነበበ ምልክት አድርግ",
    markAllAsRead: "ሁሉንም እንደተነበበ ምልክት አድርግ",
    deleteNotificationConfirm: "ይህን ማሳወቂያ መሰረዝ እንደሚፈልጉ እርግጠኛ ነዎት?",
    // Admin Link Requests
    linkRequests: "የወላጅ-ተማሪ የግንኙነት ጥያቄዎች",
    linkRequestsDescription: "ወላጆችን ከተማሪዎች ጋር ለማገናኘት የሚቀርቡ የምዝገባ ጥያቄዎችን አጽድቅ ወይም ውድቅ አድርግ",
    pendingRequestsTab: "በመጠባበቅ ላይ ያሉ ጥያቄዎች",
    approvedLinksTab: "የፀደቁ ግንኙነቶች",
    noPendingRequests: "ምንም በመጠባበቅ ላይ ያሉ ጥያቄዎች የሉም",
    pendingRequestsProcessed: "ሁሉም የወላጅ-ተማሪ ግንኙነት ጥያቄዎች ተስተናግደዋል::",
    requestDate: "የጥያቄ ቀን",
    contactInfo: "የእውቂያ መረጃ",
    approveSuccess: "ወላጅ ከተማሪ ጋር በተሳካ ሁኔታ ተገናኝቷል! ማሳወቂያ ተልኳል።",
    rejectSuccess: "የግንኙነት ጥያቄ ውድቅ ተደርጓል።",
    // Admin Announcements
    broadcastNotification: "ለተማሪዎች እና ለወላጆች የቀጥታ ማሳወቂያ ያስተላልፉ።",
    announcementSentSuccess: "ማስታወቂያው በተሳካ ሁኔታ ተልኳል!",
    failedToSendAnnouncement: "ማስታወቂያውን መላክ አልተቻለም።",
    fillTitleMessage: "እባክዎ ርዕሱን እና መልዕክቱን ይሙሉ::",
    announcementPlaceholderTitle: "ለምሳሌ፦ የፈተና ፕሮግራም ወጥቷል",
    announcementPlaceholderMessage: "ማስታወቂያዎን እዚህ ይጻፉ...",
    targetAudience: "ታላሚ ቡድን",
    everyone: "ሁሉም (ተማሪዎች እና ወላጆች)",
    allStudents: "ሁሉም ተማሪዎች",
    allParents: "ሁሉም ወላጆች",
    filterByYear: "በዓመት አጣራ (ተማሪዎች)",
    // Admin Upload
    gradeManagementPortal: "የውጤት አስተዳደር ፖርታል",
    gradeManagementDescription: "የተማሪዎችን ውጤት ይጫኑ እና ያስተዳድሩ። ውጤቶች ሲታተሙ ወላጆች በራስ-ሰር ማሳወቂያ ይደርሳቸዋል።",
    notificationsSent: "ማሳወቂያዎች ተልከዋል",
    bulkUpload: "በብዛት ይጫኑ",
    selectFile: "CSV ወይም Excel ፋይል ይምረጡ",
    csvExcelOnly: "CSV ወይም Excel ፋይሎች ብቻ",
    fileSize: "የፋይል መጠን",
    uploadProcessFile: "ፋይል ይጫኑ እና ያካሂዱ",
    addSingleGrade: "አንድ ውጤት ጨምር",
    scoreOptional: "ነጥብ (አማራጭ)",
    addGradeRecord: "የውጤት መዝገብ ጨምር",
    gradeRecords: "የውጤት መዛግብት",
    publishAllPending: "ሁሉንም በመጠባበቅ ላይ ያሉ አትም",
    studentsByYear: "ተማሪዎች በዓመት",
    showAllGrades: "ሁሉንም ውጤቶች አሳይ",
    noStudentsForYear: "ለተመረጠው ዓመት ተማሪዎች አልተገኙም።",
    notificationStatus: "ማሳወቂያ",
    sent: "ተልኳል",
    // Analytics
    noAnalyticsData: "ምንም የትንታኔ መረጃ የለም",
    ensureGradesUploaded: "እባክዎ ውጤቶች መጫናቸውን ያረጋግጡ።",
    academicAnalytics: "ዩኒቨርሲቲ አቀፍ የትምህርት ትንታኔ",
    analyticsDescription: "የዩኒቨርሲቲው አፈጻጸም፣ የትምህርት ክፍል አዝማሚያዎች እና ለአደጋ የተጋለጡ ተማሪዎች አጠቃላይ እይታ።",
    universityAvgGPA: "የዩኒቨርሲቲ አማካይ GPA",
    enrolledStudents: "የተመዘገቡ ተማሪዎች",
    totalGradesRecorded: "ጠቅላላ የተመዘገቡ ውጤቶች",
    studentsAtRisk: "ለአደጋ የተጋለጡ ተማሪዎች",
    performanceByDepartment: "አፈጻጸም በትምህርት ክፍል",
    avgGPA: "አማካይ GPA",
    generalGradeDistribution: "አጠቃላይ የውጤት ስርጭት",
    atRiskStudentsTitle: "⚠️ ለአደጋ የተጋለጡ ተማሪዎች (GPA < 2.0 ወይም የወደቁባቸው ኮርሶች)",
    studentsFlagged: "ምልክት የተደረገባቸው ተማሪዎች",
    issue: "ጉዳይ",
    action: "እርምጃ",
    hasFailedCourses: "የወደቀባቸው ኮርሶች አሉ",
    lowAcademicStanding: "ዝቅተኛ የትምህርት ደረጃ",
    notifyParent: "ወላጅ ያሳውቁ",
    noAtRiskStudents: "በአሁኑ ጊዜ ለአደጋ የተጋለጡ ተማሪዎች የሉም። በጣም ጥሩ!",
    // Reports
    academicReports: "የትምህርት ሪፖርቶች እና ትራንስክሪፕቶች",
    reportsDescription: "አጠቃላይ የትምህርት ሪፖርቶችን ያዘጋጁ እና ያውርዱ",
    exportCSV: "ወደ CSV ላክ",
    print: "አትም",
    fullTranscript: "ሙሉ ትራንስክሪፕት",
    semesterReport: "የሴሚስተር ሪፖርት",
    summaryReport: "ማጠቃለያ ሪፖርት",
    courseGrades: "የኮርስ ውጤቶች",
    officialTranscript: "ኦፊሴላዊ የትምህርት ትራንስክሪፕት",
    dateGenerated: "የተዘጋጀበት ቀን",
    overallGPA: "አጠቃላይ GPA",
    academicSummary: "የትምህርት ማጠቃለያ",
    totalCourses: "ጠቅላላ ኮርሶች",
    totalCredits: "ጠቅላላ ክሬዲቶች",
    semesters: "ሴሚስተሮች",
    noGradesAvailable: "ምንም ውጤቶች የሉም",
    officialDocumentFooter: "ይህ በዩኒቨርሲቲ ውጤት ፖርታል የተዘጋጀ ኦፊሴላዊ ሰነድ ነው",
    verificationFooter: "ለማረጋገጫ፣ የዩኒቨርሲቲውን አስተዳደር ያነጋግሩ",
    comingSoon: "ይህ ባህሪ በቅርቡ ይመጣል!",
    exportedToCSV: "ሪፖርቱ ወደ CSV ተልኳል",
    // Settings
    fullNameRequired: "ሙሉ ስም ያስፈልጋል",
    emailRequired: "ኢሜይል ያስፈልጋል",
    validEmailRequired: "ትክክለኛ ኢሜይል ያስፈልጋል",
    phoneRequired: "ስልክ ቁጥር ያስፈልጋል",
    currentPasswordRequired: "የአሁኑ የይለፍ ቃል ያስፈልጋል",
    passwordLengthRequired: "የይለፍ ቃል ቢያንስ 6 ሆሄያት መሆን አለበት",
    passwordsDoNotMatch: "የይለፍ ቃሎች አይዛመዱም",
    profileUpdatedSuccessfully: "መገለጫ በተሳካ ሁኔታ ተዘምኗል",
    errorUpdatingProfile: "መገለጫን በማዘመን ላይ ስህተት ተፈጥሯል",
    passwordChangedSuccessfully: "የይለፍ ቃል በተሳካ ሁኔታ ተቀይሯል",
    errorChangingPassword: "የይለፍ ቃል መቀየር አልተቻለም",
    saveChanges: "ለውጦችን አስቀምጥ",
    updateProfile: "መገለጫ አዘምን",
    changePassword: "የይለፍ ቃል ቀይር",
    currentPassword: "የአሁኑ የይለፍ ቃል",
    newPassword: "አዲስ የይለፍ ቃል",
    confirmPassword: "የይለፍ ቃል አረጋግጥ",
    settings: "ቅንብሮች",
    // Alerts
    academicAlertsTitle: "የትምህርት ማስጠንቀቂያዎች እና ማሳሰቢያዎች",
    alertsDescription: "ስለ ልጅዎ የትምህርት አፈጻጸም መረጃ ያግኙ",
    markAllAsRead: "ሁሉንም እንደተነበበ ምልክት አድርግ",
    alertMarkedAsRead: "ማስጠንቀቂያው እንደተነበበ ምልክት ተደርጓል",
    errorMarkingAlert: "ማስጠንቀቂያውን እንደተነበበ ምልክት ማድረግ ላይ ስህተት ተፈጥሯል",
    allAlertsMarkedAsRead: "ሁሉም ማስጠንቀቂያዎች እንደተነበበ ምልክት ተደርገዋል",
    errorMarkingAllAlerts: "ማስጠንቀቂያዎችን እንደተነበበ ምልክት ማድረግ ላይ ስህተት ተፈጥሯል",
    allAlerts: "ሁሉም ማስጠንቀቂያዎች",
    unread: "ያልተነበቡ",
    critical: "ወሳኝ",
    highPriority: "ከፍተኛ ቅድሚያ የሚሰጠው",
    noAlerts: "ምንም ማስጠንቀቂያዎች የሉም",
    allAlertsRead: "ሁሉም ማስጠንቀቂያዎች ተነብበዋል",
    noCriticalAlerts: "ምንም ወሳኝ ማስጠንቀቂያዎች የሉም",
    noAlertsToDisplay: "የሚታይ ምንም ማስጠንቀቂያ የለም",
    courseLabel: "ኮርስ",
    newBadge: "አዲስ",
    // Link Student
    linkAnotherStudent: "ሌላ ተማሪ አገናኝ",
    linkStudentDescription: "ሂደታቸውን ለመከታተል ሌላ ልጅ ወደ መለያዎ ያክሉ።",
    verifyStudentIdFirst: "እባክዎ መጀመሪያ የተማሪ መታወቂያውን ያረጋግጡ።",
    linkRequestSent: "የማገናኘት ጥያቄ በተሳካ ሁኔታ ተልኳል! የአስተዳዳሪ ማረጋገጫ በመጠበቅ ላይ።",
    linkRequestFailed: "የማገናኘት ጥያቄ መፍጠር አልተቻለም።",
    linkRequestError: "ጥያቄውን በመላክ ላይ ስህተት ተፈጥሯል ለ።",
    enterStudentId: "የተማሪ መታወቂያ ያስገቡ (ለምሳሌ፡ S12345)",
    studentVerified: "ተማሪው ተረጋግጧል!",
    submitting: "በማስገባት ላይ...",
    requestLink: "ማገናኘት ጠይቅ",
    linkAlreadyExists: "ይህ የተማሪ መታወቂያ ቀድሞውኑ ከቤተሰብ መለያ ጋር ተገናኝቷል። አንድ ተማሪ ከአንድ ወላጅ መለያ ጋር ብቻ መገናኘት ይችላል።",
    studentIdNotFound: "የተማሪ መታወቂያ አልተገኘም።",
    errorVerifyingStudent: "የተማሪ መታወቂያን በማረጋገጥ ላይ ስህተት ተፈጥሯል ለ።",
    // Registration Hints
    passwordRequirements: "የይለፍ ቃል ቢያንስ 1 ሆሄ፣ 1 ቁጥር እና 1 ልዩ ምልክት መያዝ አለበት።",
    emailSavePrompt: "የመግቢያ ኢሜይልዎ፡ {email} \n\nእባክዎ ይህን ኢሜይል ለወደፊት መግቢያዎች ያስቀምጡ!",
    emailUniqueHint: "ከተሰጠ ልዩ መሆን አለበት። በራስ-ሰር እንዲፈጠር ባዶ ይተዉት።",
    passwordHint: "ቢያንስ 1 ሆሄ፣ 1 ቁጥር፣ 1 ልዩ ምልክት (@$!%*#?&)፣ ቢያንስ 6 ሆሄያት መያዝ አለበት።",
    phoneHint: "ልዩ መሆን አለበት። ለኤስኤምኤስ ሁኔታ ዝመናዎች ጥቅም ላይ ይውላል።",
    studentIdHint: "ኦፊሴላዊ የዩኒቨርሲቲ የተማሪ መታወቂያዎን ያስገቡ (ለምሳሌ፡ UGR/1234/14)።",
    fullNameHint: "በኦፊሴላዊ ሰነዶች ላይ እንደሚታየው ሙሉ ህጋዊ ስምዎን ያስገቡ።",
    emailHint: "ትክክለኛ ኢሜይል አድራሻ ያስገቡ (ለምሳሌ፡ student@university.edu)።",
    confirmPasswordHint: "ለማረጋገጥ ከላይ ያለውን ተመሳሳይ የይለፍ ቃል እንደገና ያስገቡ።",
    phoneFormatHint: "ትክክለኛ ስልክ ቁጥር ያስገቡ (ለምሳሌ፡ +251-911-234-567)።",
    // Grade Details
    gradeDetailsTitle: "የውጤት ዝርዝሮች",
    gradeNotFound: "ውጤት አልተገኘም",
    gradeNotFoundMessage: "የተጠየቀው ውጤት ሊገኝ አልቻለም።",
    goBack: "ተመለስ",
    studentInformation: "የተማሪ መረጃ",
    studentName: "የተማሪ ስም",
    letterGrade: "የፊደል ውጤት",
    scoreLabel: "ውጤት",
    gradePoint: "የውጤት ነጥብ",
    performanceScore: "የአፈጻጸም ውጤት",
    uploadedDate: "የተጫነበት ቀን",
    uploadedBy: "የጫነው አካል",
    parentsNotified: "ወላጆች ተነግሯቸዋል",
    yes: "አዎ",
    no: "አይ",
    performanceEvaluation: "የአፈጻጸም ግምገማ",
    percentage: "መቶኛ",
    scoreRatio: "የውጤት ጥምርታ",
    gpaContribution: "ለጂፒኤ አስተዋጽኦ",
    printReport: "ሪፖርት አትም",
    backToGrades: "ወደ ውጤቶች ተመለስ",
    // Attendance Management
    attendanceManagementTitle: "የመገኘት አስተዳደር",
    selectStudent: "ተማሪ ይምረጡ",
    recordAttendance: "መገኘት መዝግብ",
    attendanceRecordedSuccess: "መገኘት በተሳካ ሁኔታ ተመዝግቧል!",
    errorRecordingAttendance: "መገኘት በመዝገብ ላይ ስህተት ተፈጥሯል",
    pleaseEnterAllFields: "እባክዎ ሁሉንም አስፈላጊ መረጃዎች ያስገቡ",
    // New Features
    auditLogs: "የኦዲት መዝገቦች",
    academicCalendar: "የአካዳሚክ ካላንደር",
    courseResources: "የትምህርት ግብዓቶች",
    feeManagement: "የክፍያ አስተዳደር",
    library: "ቤተ-መጽሐፍት",
    idCard: "የመታወቂያ ካርድ",
    gradeAppeals: "የውጤት ይግባኝ",
    calendar: "ካላንደር",
    resources: "ግብዓቶች",
    calendar: "ካላንደር",
    resources: "ምንጮች",
    fees: "ክፍያዎች",
    schedule: "መርሃ ግብር",
    notificationPreference: "የማሳወቂያ ምርጫ",
    receiveNotificationsVia: "ማሳወቂያዎችን እንዴት መቀበል ይፈልጋሉ?",
    emailOnly: "በኢሜይል ብቻ",
    smsOnly: "በኤስኤምኤስ (ስልክ) ብቻ",
    bothEmailAndSms: "በሁለቱም (ኢሜይል እና ኤስኤምኤስ)",
    onlineExams: "የመስመር ላይ ፈተናዎች",
    startExam: "ፈተና ጀምር",
    next: "ቀጣይ",
    back: "ተመለስ",
    submitExam: "ፈተናውን አቅርብ",
    timeLeft: "ቀሪ ጊዜ",
    question: "ጥያቄ",
    finalSubmit: "በመጨረሻ ላክ",
    addAdmin: "አስተዳዳሪ ጨምር",
    manageRecentGrades: "የቅርብ ጊዜ የውጤት ማስገባቶችን ያስተዳድሩ",
    errorLoadingDashboard: "ዳሽቦርዱን በመጫን ላይ ስህተት ተፈጥሯል",
    retry: "እንደገና ይሞክሩ",
    addAdministrator: "አስተዳዳሪ ማከል",
    addNewAdministrator: "አዲስ አስተዳዳሪ ጨምር",
    grantAdminAccess: "ለአዲስ ተጠቃሚ የአስተዳደር መብት ይስጡ",
    createAdminAccount: "የአስተዳዳሪ መለያ ፍጠር",
    addingAdministrator: "አስተዳዳሪ እየታከለ ነው...",
    securityNote: "የደህንነት ማሳሰቢያ",
    adminSecurityWarning: "ይህ አዲስ አስተዳዳሪ ተማሪዎችን፣ ውጤቶችን እና የስርዓት ቅንብሮችን ለማስተዳደር ሙሉ መብት ይኖረዋል። ፍቃዱን ለሚገባው ሰው መስጠትዎን ያረጋግጡ።",
    totalStudents: "ጠቅላላ ተማሪዎች",
    totalParents: "ጠቅላላ ወላጆች",
    totalGrades: "ጠቅላላ ውጤቶች",
    pendingRequests: "በመጠባበቅ ላይ ያሉ ጥያቄዎች",
    generalAdministration: "ጠቅላላ አስተዳደር",
    itDepartment: "የአይቲ ክፍል",
    academicRegistry: "የአካዳሚክ መዝገብ ቤት",
    financeOffice: "የፋይናንስ ቢሮ",
    studentAffairs: "የተማሪዎች ጉዳይ",
    adminAddedSuccess: "አዲስ አስተዳዳሪ በተሳካ ሁኔታ ታክሏል!",
    failedToAddAdmin: "አስተዳዳሪ ማከል አልተቻለም",
    confirmRemoveGrades: "የተመረጡትን {count} ውጤቶች ከቅርብ ጊዜ ማሳያ ያስወግዱ?",
    confirmRemoveAllGrades: "ሁሉንም የቅርብ ጊዜ ውጤቶች ከማሳያ ያስወግዱ?",
    noGradesSelectedToRemove: "ለማስወገድ የተመረጡ ውጤቶች የሉም።",
    passwordsDoNotMatch: "የይለፍ ቃል አይዛመድም",
    fullNamePlaceholder: "ሙሉ ስም ያስገቡ"
  },
  // Oromo translations

  // Oromo translations
  om: {
    studentManagement: "Maamulka Barafka",
    manageStudentInformation: "Maamulka macluumaadka barafka, cusbooneysiinta iyo kaydka barafka",
    confirmDeleteStudent: "Ma hubtaa inaad rabto inaad tirtirto barafkaan? Tani waxaa laga yaabi karaa.",
    studentUpdatedSuccessfully: "Barafka si guul leh ayaa la cusboonaysiiyay!",
    errorUpdatingStudent: "Khalad ayaa dhacay maxay ku saabsan cusbooneysiinta barafka",
    errorDeletingStudent: "Khalad ayaa dhacay maxay ku saabsan tirtirida barafka",
    studentDeletedSuccessfully: "Barafka si guul leh ayaa la tirtiray!",
    name: "Magac",
    save: "Kaydi",
    edit: "Tafatir",
    delete: "Tirtir",
    welcome: "Akam Nabsi",
    student: "Barata",
    parent: "Walgii",
    admin: "Gestuu",
    teacher: "Barsiisaa",
    teacherDashboard: "Dhashboordii Barsiisaa",
    logout: "Ba'uu",
    home: "Mana",
    dashboard: "Dhashboordii",
    profile: "Proofayilii",
    support: "Deeggarsa",
    uploadProfilePicture: "Fakkii Proofayilii Ol-fe'i",
    grades: "Qabxii",
    notifications: "Odeessa",
    courses: "Kursii",
    gpa: "GPA",
    credits: "Kireedidi",
    courseCode: "Koodii Kursii",
    courseName: "Maqaa Kursii",
    myAssignments: "Hojiiwwan Koo",
    messages: "Ergaawwan",
    analytics: "Xiinxala Sirna",
    enhancedAnalytics: "Xiinxala Mul'ataa Ol'aanaa",
    manageStudents: "Barattoota To'adhu",
    gradeApprovals: "Mirkaneessa Qabxii",
    examApprovals: "Mirkaneessa Qormaataa",
    reportCardGen: "Qophii Kaardii",
    createOnlineExam: "Qormaata Onlaayinii Uumi",
    editProfile: "Proofayilii Haaromsi",
    semester: "Samiistara",
    grade: "Dargii",
    score: "Sakkata",
    status: "Haala",
    published: "Dabalata",
    login: "Gal",
    register: "Galmeessi",
    email: "Imeel",
    password: "Jecha Irree",
    confirmPassword: "Jecha Irree Dhiyaari",
    fullName: "Maqaa Waliigalaa",
    studentId: "Lambar Barata",
    phone: "Sirna",
    department: "Kutaa",
    year: "Waggaa",
    relationship: "Haala Walii",
    yourName: "Maqaa Keessan",
    yourEmail: "Imeel Keessan",
    yourPhone: "Sirna Keessan",
    childStudentId: "Lambar Barata Daa'imaa",
    approve: "Deebii",
    reject: "Hin gatoomiin",
    actions: "Tinnoonni",
    approveLink: "Linkii Deebii",
    rejectLink: "Linkii Hin Gatoomiin",
    pending: "Dura duree jira",
    approved: "Deebiifameera",
    rejected: "Hin deebiifamne",
    active: "Barbaaddaa",
    newNotification: "Haaraa",
    parentAccess: "Barbaadda Walgii",
    passedCourses: "Kursiiwwan Qusnuman",
    totalCredits: "Kireedidi Waliigalaa",
    coursesTaken: "Kursiiwwan Baratan",
    academicRecord: "Gabaan Dhaabbata",
    currentGPA: "GPA Ammaa",
    welcomeMessage: "Akam Nabsi, {name}!",
    studentIdLabel: "Lambar Barata: {id}",
    computerScience: "Komepiyuter Siinsii",
    yearNumber: "Waggaa {year}",
    selectLanguage: "Afaan Meeqqi",
    english: "Ingliffa",
    amharic: "Afaan Oromo",
    oromo: "Afaan Oromoo",
    somali: "Soomaali",
    tigrinya: "Tigriigna",
    contactAdvisor: "Kan Advaayizariin Dhagee",
    downloadReport: "Ripootiin Dhaadi",
    academicPerformance: "Adeemsa Akaadimik",
    autoUpdated: "Gat-kan Dhaabbata",
    alertsNotifications: "Dhageeysiyadaan Odeessiyada",
    academicProgress: "Adeemsa Akaadimik",
    academicAdvisory: "Gorsa Akkaadeemii",
    academicAdvisoryMessage: "Akeekkachiisa Murteessaa: Galmeen keenya akka agarsiisutti, qabxiiwwan gadi aanaa (D ykn F) tokko ykn isaa ol argatteetta. Barnoota kee Yuunivarsiitii keessatti itti fufuuf, GPA quubsaa qabaachuu qabda. Maaloo qabxiiwwan kee itti aanan irratti xiyyeeffadhu yoo gargaarsa barbaadde immoo gorsaa akkaadeemii kee waliin mari'adhu.",
    advisor: "Advaayizari",
    subject: "Mata",
    yourMessage: "Eeygaagu",
    writeMessagePlaceholder: "Eeygaagu halkan barre...",
    cancel: "Haqi",
    sendMessage: "Eeyga soo dir",
    regardingAcademicProgress: "Eeg {studentName} Adeemsa Akaadimik",
    loginFailedMessage: "Hiikkamsi isii faliif. Maaree itti fayyadamtu mirkaneessi.",
    universityGradePortal: "Wiirtuuwwan Qooda Qindeessaa",
    transparentAcademicMonitoring: "Karaa murtaa'aa fi qindeessaa barnoota hundaarsuun dursa barattuu hundaarsa",
    selectYourRole: "Roolii kee filadhu",
    studentLogin: "Galma Barata",
    parentLogin: "Galma Walgitu",
    adminLogin: "Galma Gesteessa",
    viewGradesAndAcademicProgress: "Qoodota kee fi dursa barattuu kee ilaali",
    monitorChildAcademicPerformance: "Adeemsa barattuu daa'imaa kee hundaari",
    uploadAndManageStudentGrades: "Qoodota barattootaa olkaa'ii fi gadeessi",
    teacherLogin: "Galma Barsiisaa",
    uploadGradesByYearAndSemester: "Qodaawwan waggaa fi samiistaridhaan ol-fe'i",
    recentUploads: "Ol-fe'iinsa Dhiyoo",
    adminReviewRequired: "Mirkaneessa Bulchiinsaa Barbaachisa",
    academicYear: "Waggaa Barnootaa",
    demo: "Ku'ufama",
    loginAs: "Galuun",
    demoApplication: "Ku'ufama Gosa",
    demoApplicationDescription: "Kunisni qoodota barnootaa karaa murtaa'aa fi qindeessaa argachuu asitti gargaara. Maaree isii fayyadami fi galma dhiibi.",
    newUserRegisterFirst: "Fayyadama haaraa? Dura duree galmeessi",
    registerAsStudent: "Barataan galmeessi",
    enterYourEmail: "Imeelii kee galchi",
    enterYourPassword: "Jecha irree kee galchi",
    fullNameRequired: "Maqaa waliigalaa barbaachisa",
    studentIdRequired: "Lambar barataa barbaachisa",
    validEmailRequired: "Imeelii dhugaa barbaachisa",
    passwordLengthRequired: "Jecha irreen yoo xiqqaate qubee 6 qabaachuu qaba",
    passwordsDoNotMatch: "Jecha irree wal hin qabne",
    phoneRequired: "Lakkoofsa sirnaa barbaachisa",
    agreeToTermsRequired: "Haala itti fayyadamtu dhiyeessuu qaba",
    studentAlreadyExists: "Barataan kun lambara iddoo ykn imelii isaa jira",
    studentRegistrationSuccess: "Galmeessi barataa xumurameera! Amma galmaa argachuu dandeessa.",
    studentRegistration: "Galmeessi Barataa",
    registerAsStudentToAccessPortal: "Wiirtuuwwan barataa keessan irratti galmaa argachuuf barataan galmeessi",
    fullNamePlaceholder: "Abebe Kebede",
    studentIdPlaceholder: "UGR/1234/14",
    emailPlaceholder: "barata@fakkeessaa.com",
    passwordPlaceholder: "Yoo xiqqaate qubee 6",
    confirmPasswordPlaceholder: "Jecha irree kee mirkaneessi",
    phonePlaceholder: "+251 911 223344",
    selectDepartment: "Kuta filadhu",
    year1: "Waggaa 1",
    year2: "Waggaa 2",
    year3: "Waggaa 3",
    year4: "Waggaa 4",
    year5: "Waggaa 5",
    agreeToShareAcademicInfo: "Wiirtuuwwan barattuu kee walgitoota galmeeffaman irratti qoodaaffachuun isaanis hubachiisa qoodichaaf walitti qabachuu dhiyeessaa jira",
    alreadyHaveAccount: "Baratamicha jira?",
    loginHere: "Galmee kana irratti",
    parents: "Walgitoota:",
    electricalEngineering: "Injiniyerawwi Elektrikaa",
    mechanicalEngineering: "Injiniyerawwi Meekaanikaa",
    civilEngineering: "Injiniyerawwi Sivilii",
    medicine: "Qalbi",
    businessAdministration: "Gadaawwi Daldala",
    law: "Seera",
    agriculture: "Biiftuu",
    notifyParent: "Walgittoota beeksisi",
    messageToParent: "Ergaa walgittootaaf",
    notificationTitle: "Mata duree beeksisaa",
    actionIssueDescription: "Ibsa gochaa/dhimmaa",
    sendNotification: "Beeksisa ergi",
    directChat: 'Mari’ii Kallattii',
    nationalId: 'Waraqaa Eenyummaa Naannoo (Fayda)',
    scanQRToRegister: 'Galmaa’uuf QR Skani godhaa',
    quickRegistration: 'Galmee Ariifachisaa',
    idVerified: 'Eenyummaan Mirkanaa’eera',
    idPending: 'Eenyummaan Mirkaneessa Eeggachaa Jira',
    notificationSentSuccessfully: "Beeksisi milkaa'inaan ergameera",
    studentIssueReport: "Gabaasa dhimma barataa",
    administrativeAction: "Tarkaanfii bulchiinsaa",
    regulationProblem: "Rakkoo Seeraa",
    unregulatedAction: "Gocha/dhimma hin qindofne",
    notLinkedToParent: "Walgittoota waliin hin hidhamne",
    linkedToParent: "Walgituu waliin hidhameera ({name})",
    searchByIdOrName: "Lambar barataa ykn maqaan barbaadi...",
    attendance: "Hirmaannaa",
    attendanceRate: "Heerka Hirmaannaa",
    attendanceHistory: "Seenaa Hirmaannaa",
    totalSessions: "Waliigala Hirmaannaa",
    present: "Argaman",
    absent: "Hafan",
    late: "Turatan",
    excused: "Hayyamameef",
    remarks: "Yaada",
    date: "Guyyaa",
    welcomeBack: "Baga Nagaan Deebitan",
    adminDashboard: "Daashboordii Bulchiinsaa",
    viewMyGrades: "Qabxii Koo Ilaali",
    viewChildGrades: "Qabxii Mucaa Ilaali",
    linkNewStudent: "Barataa Haaraa Walqabsiisi",
    sendAnnouncement: "Beeksisa Ergi",
    manageLinkRequests: "Gaaffii Walqabsiisaa To'adhu",
    uploadGrades: "Qabxii Fe'i",
    attendanceRecord: "Galmee Hirmaannaa",
    recentGrades: "Qabxiiwwan Dhiyoo",
    noRecentGrades: "Qabxiin dhiyoo hin jiru",
    loadingDashboard: "Dhashboordii ol-fe'aa jira...",
    loading: "Ol-fe'aa jira...",
    department: "Kutaa Barnootaa",
    currentGPA: "GPA Ammaa",
    year: "Waggaa",
    academicAdvisory: "Gorsa Barnootaa",
    regardingAcademicProgress: "Waa'ee Raawwii Barnootaa {studentName}",
    subject: "Mata Duree",
    yourMessage: "Ergaa Keessan",
    cancel: "Haqi",
    sendMessage: "Ergaa Ergi",
    advisor: "Gorsaa",
    email: "Iimeeyilii",
    student: "Barataa",
    pending: "Eeggataa Jira",
    loadingGrades: "Qabxii Fe'aa Jira...",
    noGradesYet: "Qabxiin Hin Jiru",
    noGradesYetMessage: "Qabxiin keessan yeroo barsiisaan fe'amu asitti mul'ata.",
    currentSemester: "Simisteera Ammaa",
    detailedGradeView: "Ibsa guutuu qabxiiwwan hunda",
    noGradesFound: "Qabxiin Hin Argamne",
    noGradesRecordedMessage: "Barataa kanaaf hanga ammaatti qabxiin hin galmoofne.",
    creditHours: "Sa'aatii Kireeditii",
    referenceAllYears: "Waggoota Hunda Ilaali",
    noStudentsFound: "Barattoonni ulaagaa kanaan walgitan hin argamne.",
    sending: "Ergaa Jira...",
    type: "Gosa",
    excellent: "Baay'ee Gaarii",
    viewPresenceRecords: "Galmee hirmaannaa koorsii hunda ilaali",
    noAttendanceRecords: "Galmeen hirmaannaa hin argamne",
    noNotificationsTitle: "Odeessi Hin Jiru",
    noNotificationsMessage: "Yeroo ammaa odeessa tokkollee hin qabdan",
    notification: "Odeessa",
    markAsRead: "Akka dubbifameetti mallatteessi",
    markAllAsRead: "Hunda akka dubbifameetti mallatteessi",
    deleteNotificationConfirm: "Odeessa kana haquu barbaaduu keessan mirkaneessituu?",
    // Admin Link Requests
    linkRequests: "Gaaffii Walqabsiisa Maatii-Barataa",
    linkRequestsDescription: "Gaaffiiwwan galmee maatii barattoota waliin walqabsiisuu mirkaneessi ykn kufaa godhi",
    pendingRequestsTab: "Gaaffiiwwan Eeggataa Jiran",
    approvedLinksTab: "Walqabsiisa Mirkanaa'an",
    noPendingRequests: "Gaaffiiwwan Eeggataa Jiran Hin Jiran",
    pendingRequestsProcessed: "Gaaffiiwwan walqabsiisa maatii-barataa hundi keessummeeffamaniiru.",
    requestDate: "Guyyaa Gaaffii",
    contactInfo: "Odeeffannoo Quunnamtii",
    active: "Si'aayaa",
    approveSuccess: "Maatiin barataa waliin milkaa'inaan walqabateera! Odeessi ergameera.",
    rejectSuccess: "Gaaffiin walqabsiisaa kufaa ta'eera.",
    // Admin Announcements
    broadcastNotification: "Beeksisa qindaa'aa barattootaa fi maatiif dabarsi.",
    announcementSentSuccess: "Beeksisni milkaa'inaan ergameera!",
    failedToSendAnnouncement: "Beeksisa ergurratti rakkoon uumame.",
    fillTitleMessage: "Maaloo mata-duree fi ergaa guutaa.",
    announcementPlaceholderTitle: "Fkn: Sagantaan Qormaataa Gadhiifameera",
    announcementPlaceholderMessage: "Beeksisa keessan asirratti barreessaa...",
    targetAudience: "Gareen Ilaallatu",
    everyone: "Hunda (Barattoota fi Maatii)",
    allStudents: "Barattoota Hunda",
    allParents: "Maatii Hunda",
    filterByYear: "Waggaan Calali (Barattoota)",
    // Admin Upload
    gradeManagementPortal: "Poortaalii Bulchiinsa Qabxii",
    gradeManagementDescription: "Qabxii barattootaa fe'aa fi bulchaa. Yeroo qabxiin maxxanfamu maatiin ofumaan beeksisa argatu.",
    notificationsSent: "Odeessi Ergame",
    bulkUpload: "Baay'inaan Fe'uu",
    selectFile: "Faayilii CSV ykn Excel Filadhu",
    csvExcelOnly: "Faayiloota CSV ykn Excel qofa",
    fileSize: "Hanga Faayilii",
    uploadProcessFile: "Fe'i fi Adeemsisi",
    addSingleGrade: "Qabxii Tokko Dabali",
    scoreOptional: "Qabxii (Filannoo)",
    addGradeRecord: "Galmee Qabxii Dabali",
    gradeRecords: "Galmeewwan Qabxii",
    publishAllPending: "Kan Eeggataa Jiran Hunda Maxxansi",
    studentsByYear: "Barattoota Waggaan",
    showAllGrades: "Qabxii Hunda Agarsiisi",
    noStudentsForYear: "Barattoonni waggaa filatameef hin argamne.",
    notificationStatus: "Odeessa",
    sent: "Ergameera",
    // Analytics
    noAnalyticsData: "Qaaccessi daataa hin jiru",
    ensureGradesUploaded: "Maaloo qabxiin fe'amuu isaa mirkaneeffadhaa.",
    academicAnalytics: "Qaaccessa Barnootaa Yuunivarsiitii",
    analyticsDescription: "Waa'ee raawwii yuunivarsiitii, haala dipaartimantii, fi barattoota balaaf saaxilamanii ibsa bal'aa.",
    universityAvgGPA: "Giddugaleessa GPA Yuunivarsiitii",
    enrolledStudents: "Barattoota Galmaa'an",
    totalGradesRecorded: "Qabxiiwwan Galmaa'an Waliigala",
    studentsAtRisk: "Barattoota Balaaf Saaxilaman",
    performanceByDepartment: "Raawwii Dipaartimantiin",
    avgGPA: "Giddugaleessa GPA",
    generalGradeDistribution: "Raabsa Qabxii Waliigalaa",
    atRiskStudentsTitle: "⚠️ Barattoota Balaaf Saaxilaman (GPA < 2.0 ykn Qabxii Kufaa)",
    studentsFlagged: "Barattoota Adda Ba'an",
    issue: "Dhimma",
    action: "Tarkaanfii",
    hasFailedCourses: "Koorsii Kufaa Qaba",
    lowAcademicStanding: "Sadarkaa Barnootaa Gad-aanaa",
    notifyParent: "Maatii Beeksisi",
    noAtRiskStudents: "Barattoonni balaaf saaxilaman yeroo ammaa hin jiran. Hojii gaarii!",
    // Reports
    academicReports: "Gabaasa Barnootaa fi Tiraanskiriptii",
    reportsDescription: "Gabaasa barnootaa guutuu qopheessaa fi buufadhaa",
    exportCSV: "Gara CSV Ergi",
    print: "Maxxansi",
    fullTranscript: "Tiraanskiriptii Guutuu",
    semesterReport: "Gabaasa Simisteeraa",
    summaryReport: "Gabaasa Gabaabaa",
    courseGrades: "Qabxii Koorsii",
    officialTranscript: "Tiraanskiriptii Barnootaa Seera-qabeessa",
    dateGenerated: "Guyyaa Qophaa'e",
    overallGPA: "GPA Waliigalaa",
    academicSummary: "Gabaasa Barnootaa",
    totalCourses: "Baay'ina Koorsii",
    totalCredits: "Baay'ina Kireditii",
    semesters: "Simisteerota",
    noGradesAvailable: "Qabxiin hin jiru",
    officialDocumentFooter: "Kun sanada seera-qabeessa Poortaalii Qabxii Yuunivarsiitiin qophaa'edha",
    verificationFooter: "Mirkaneessuuf, bulchiinsa yuunivarsiitii quunnamaa",
    comingSoon: "Amalli kun dhihootti ni dhufa!",
    exportedToCSV: "Gabaasni gara CSV ergameera",
    // Settings
    emailRequired: "Imeeliin ni barbaachisa",
    validEmailRequired: "Imeeliin sirrii ta'e ni barbaachisa",
    phoneRequired: "Lakkoofsi bilbilaa ni barbaachisa",
    currentPasswordRequired: "Jechi darbii ammaa ni barbaachisa",
    passwordLengthRequired: "Jechi darbii yoo xiqqaate qubee 6 ta'uu qaba",
    passwordsDoNotMatch: "Jechi darbii wal hin simu",
    profileUpdatedSuccessfully: "Piroofayiliin milkaa'inaan haaromeera",
    errorUpdatingProfile: "Piroofayilii haaromsuu irratti rakkoon uumame",
    passwordChangedSuccessfully: "Jechi darbii milkaa'inaan jijjiirameera",
    errorChangingPassword: "Jechu darbii jijjiiruu hin dandeenye",
    updateProfile: "Piroofayilii Haaromsi",
    changePassword: "Jecha Darbii Jijjiiri",
    newPassword: "Jecha Darbii Haaraa",
    confirmPassword: "Jecha Darbii Mirkaneessi",
    settings: "Qindoomina",
    // Alerts
    academicAlertsTitle: "Akeekkachiisa Barnootaa",
    alertsDescription: "Waa'ee raawwii barnoota mucaa keessanii odeeffannoo argadhaa",
    markAllAsRead: "Hunda Dubbisuu Mirkaneessi",
    alertMarkedAsRead: "Akeekkachiisni dubbifameera",
    errorMarkingAlert: "Akeekkachiisa dubbisuu irratti rakkoon uumame",
    allAlertsMarkedAsRead: "Akeekkachiisni hundi dubbifameera",
    errorMarkingAllAlerts: "Akeekkachiisa hunda dubbisuu irratti rakkoon uumame",
    allAlerts: "Akeekkachiisa Hunda",
    unread: "Kan Hin Dubbifamne",
    critical: "Murteessaa",
    highPriority: "Dursa Olaanaa",
    noAlerts: "Akeekkachiisni Hin Jiru",
    allAlertsRead: "Akeekkachiisni hundi dubbifameera",
    noCriticalAlerts: "Akeekkachiisni murteessaan hin jiru",
    noAlertsToDisplay: "Akeekkachiisni agarsiifamu hin jiru",
    courseLabel: "Koorsii",
    newBadge: "HAARAA",
    // Link Student
    linkAnotherStudent: "Barataa Biraa Aganaan",
    linkStudentDescription: "Guddina isaanii hordofuuf mucaa biraa herrega keessanitti dabalaa.",
    verifyStudentIdFirst: "Maaloo duraan eenyummaa barataa mirkaneessaa.",
    linkRequestSent: "Gaaffiin walitti hidhuu milkaa'inaan ergameera! Mirkaneessa bulchaa eegaa jira.",
    linkRequestFailed: "Gaaffii walitti hidhuu uumuu hin dandeenye.",
    linkRequestError: "Gaaffii erguu irratti rakkoon uumame.",
    enterStudentId: "Eenyummaa Barataa Galchaa (fkn, S12345)",
    studentVerified: "Barataan Mirkanaa'eera!",
    submitting: "Galchaa jira...",
    requestLink: "Walitti Hidhuu Gaafadhu",
    linkAlreadyExists: "Eenyummaan barataa kun duraan herrega maatii wajjin walitti hidhameera. Herrega waldii tokko qofatu barataa wajjin walitti hidhamuu danda'a.",
    studentIdNotFound: "Eenyummaan barataa hin argamne.",
    errorVerifyingStudent: "Eenyummaa barataa mirkaneessuu irratti rakkoon uumame.",
    // Registration Hints
    passwordRequirements: "Jechi darbii yoo xiqqaate qubee 1, lakkoofsa 1, fi mallattoo addaa 1 qabaachuu qaba.",
    emailSavePrompt: "Imeelii seenusa keessanii: {email} \n\nMaaloo imeelii kana seensa gara fuulduraatiif kaa'adhaa!",
    emailUniqueHint: "Yoo kenname adda ta'uu qaba. Ofiin akka uumamuf duwwaa dhiisaa.",
    passwordHint: "Yoo xiqqaate qubee 1, lakkoofsa 1, mallattoo addaa 1 (@$!%*#?&), fi qubee 6 qabaachuu qaba.",
    phoneHint: "Adda ta'uu qaba. Odeeffannoo haala SMS'f tajaajila.",
    studentIdHint: "Eenyummaa barataa yuunivarsiitii keessanii sirrii galchaa (fkn, UGR/1234/14).",
    fullNameHint: "Maqaa keessan guutuu seera-qabeessa sanada irratti mul'atu galchaa.",
    emailHint: "Teessoo imeelii sirrii galchaa (fkn, student@university.edu).",
    confirmPasswordHint: "Mirkaneessuuf jecha darbii walfakkaataa irra deebiin galchaa.",
    phoneFormatHint: "Lakkoofsa bilbilaa sirrii galchaa (fkn, +251-911-234-567).",
    // Grade Details
    gradeDetailsTitle: "Zarzirii Qabxii",
    gradeNotFound: "Qabxiin Hin Argamne",
    gradeNotFoundMessage: "Qabxiin gaafatame hin argamne.",
    goBack: "Deebi'i",
    studentInformation: "Odeeffannoo Barataa",
    studentName: "Maqaa Barataa",
    letterGrade: "Qabxii Qubee",
    scoreLabel: "Qabxii",
    gradePoint: "Qabxii Qabxii (Grade Point)",
    performanceScore: "Qabxii Raawwii",
    uploadedDate: "Guyyaa Fe'ame",
    uploadedBy: "Kan Fe'e",
    parentsNotified: "Maatiin Beeksisamaniiru",
    yes: "Eeyyee",
    no: "Lakki",
    performanceEvaluation: "Gimseessa Raawwii",
    percentage: "Dhibbeentaa",
    scoreRatio: "Reeshiyoo Qabxii",
    gpaContribution: "Gumaacha GPA",
    printReport: "Gabaasa Maxxansi",
    backToGrades: "Gara Qabxiileetti Deebi'i",
    // Attendance Management
    attendanceManagementTitle: "Bulchiinsa Argamaa",
    selectStudent: "Barataa Filadhu",
    recordAttendance: "Argama Galmeessi",
    attendanceRecordedSuccess: "Argamni milkaa'inaan galmaa'eera!",
    errorRecordingAttendance: "Argama galmeessuu irratti rakkoon uumame",
    pleaseEnterAllFields: "Maaloo dirree barbaachisaa hunda galchaa",
    // New Features
    auditLogs: "Galmeewwan Ooditii",
    academicCalendar: "Kaalandara Akkaadaamii",
    courseResources: "Meeshaalee Barnootaa",
    feeManagement: "Bulchiinsa Kafaltii",
    library: "Mana Kitaabaa",
    idCard: "Kaardii Eenyummaa",
    gradeAppeals: "Ol-iyyannoo Qabxii",
    calendar: "Kaalandara",
    resources: "Meeshaalee",
    fees: "Kafaltiiwwan",
    schedule: "Sagantaa",
    onlineExams: "Qormaata Onlaayinii",
    addAdmin: "Bulchaa Dabaluu",
    manageRecentGrades: "Qabxiiwwan dhiyoo bulchuu",
    errorLoadingDashboard: "Dhashboordii fe'uutti dogoggora",
    retry: "Irra Deebi'ii Yaali",
    addAdministrator: "Bulchaa Dabaluu",
    addNewAdministrator: "Bulchaa Haaraa Dabaluu",
    grantAdminAccess: "Fayyadamaa haaraaf mirga bulchiinsaa kenni",
    createAdminAccount: "Herrega Bulchaa Uumi",
    addingAdministrator: "Bulchaa dabalamaa jira...",
    securityNote: "Yaadannoo Nageenyaa",
    adminSecurityWarning: "Bulchaan haaraan kun barattoota, qabxiiwwan fi qindaa'ina sirna bulchuuf mirga guutuu ni qabaata. Namaaf mirga kennuu kee mirkaneessi.",
    generalAdministration: "Bulchiinsa Waliigalaa",
    itDepartment: "Kutaa IT",
    academicRegistry: "Galmee Barnootaa",
    financeOffice: "Waajjira Maallaqaa",
    studentAffairs: "Dhimma Baratootaa",
    adminAddedSuccess: "Bulchaan haaraan milkaa'inaan dabalame!",
    failedToAddAdmin: "Bulchaa dabaluun hin milkoofne",
    confirmRemoveGrades: "Qabxiiwwan {count} filaman agarsiisa dhiyoo irraa haquu?",
    confirmRemoveAllGrades: "Qabxiiwwan dhiyoo hunda agarsiisa irraa haquu?",
    noGradesSelectedToRemove: "Qabxiiwwan haquuf filaman hin jiru.",
    totalStudents: "Barattoota Waliigalaa",
    totalParents: "Maatiwwan Waliigalaa",
    totalGrades: "Qabxiiwwan Waliigalaa",
    pendingRequests: "Gaaffilee Eegamaa Jiran"
  },
  // Somali translations
  so: {
    welcome: "Soo Dhawoow",
    student: "Xarun",
    parent: "Hooy",
    admin: "Maamul",
    teacher: "Macallin",
    teacherDashboard: "Dashboard-ka Macallinka",
    logout: "Ka bax",
    home: "Hoyga",
    dashboard: "Dashboard",
    profile: "Profile-ka",
    support: "Taageero",
    uploadProfilePicture: "Soo rar Sawirka Profile-ka",
    grades: "Darajooyinka",
    notifications: "Ogaysiiso",
    courses: "Kursiyada",
    gpa: "GPA",
    credits: "Kareedit",
    courseCode: "Koodhka Kursiga",
    courseName: "Magaca Kursiga",
    myAssignments: "Mawduucyadayda",
    messages: "Farriimaha",
    analytics: "Falanqaynta Nidaamka",
    enhancedAnalytics: "Falanqaynta Muuqaalka Horumarsan",
    manageStudents: "Maamul Ardayda",
    gradeApprovals: "Ansixinta Darajooyinka",
    examApprovals: "Ansixinta Imtixaanada",
    reportCardGen: "Diyaarinta Kaarka Warbixinta",
    createOnlineExam: "Abuur Imtixaan Online ah",
    editProfile: "Wax ka baddal Profile-ka",
    semester: "Samiistar",
    grade: "Qadarka",
    score: "Heerka",
    status: "Xaaladda",
    published: "Shaqsiisi",
    login: "Gali",
    register: "Diiwaangel",
    email: "Imeel",
    password: "Furaha",
    confirmPassword: "Sicirka Furaha",
    fullName: "Magaca Guud",
    studentId: "Lambarka Xarunta",
    phone: "Telefoon",
    department: "Qeyb",
    year: "Sannad",
    relationship: "Xiriirka",
    yourName: "Magacooda",
    yourEmail: "Imeelkaaga",
    yourPhone: "Telefoinkaaga",
    childStudentId: "Lambarka Xarunta Ilaha",
    approve: "Ogolow",
    reject: "Diid",
    actions: "Tijaabiyo",
    approveLink: "Ogolow Link",
    rejectLink: "Diid Link",
    pending: "Sugna",
    approved: "Ogolay",
    rejected: "Diiday",
    active: "Falla",
    newNotification: "Cusub",
    parentAccess: "Helitaanka Hooyga",
    passedCourses: "Kursiyada Dhicinta",
    totalCredits: "Wadarta Kareedit",
    coursesTaken: "Kursiyada Latahay",
    academicRecord: "Qormooyinka Waxbarashada",
    currentGPA: "GPA Hadda",
    welcomeMessage: "Soo Dhawoow, {name}!",
    studentIdLabel: "Lambarka Xarunta: {id}",
    computerScience: "Saynis Computer",
    yearNumber: "Sannad {year}",
    selectLanguage: "Dooro Tonga",
    english: "Ingiriis",
    amharic: "Amaric",
    oromo: "Oromo",
    somali: "Soomaali",
    contactAdvisor: "La Xiriir Adeegsuushi",
    downloadReport: "Dajin Soo Dhigi",
    academicPerformance: "Adeegsuusha Waxbarashada",
    autoUpdated: "Wax Ku Dhijinta Aafrika",
    alertsNotifications: "Digniin & Ogaysiiso",
    academicProgress: "Siiyada Waxbarashada",
    advisor: "La-taliye",
    subject: "Mawduuca",
    yourMessage: "Farriintaada",
    writeMessagePlaceholder: "Fariintaada halkan ku qor...",
    cancel: "Jooji",
    sendMessage: "Dir Farriin",
    loadingGrades: "Laga soo shubayaa darajooyinka...",
    noGradesYet: "Wali Ma Jiraan Darajooyin",
    noGradesYetMessage: "Darajooyinkaagu waxay halkan ka soo muuqan doonaan marka macalinkaagu soo geliyo.",
    currentSemester: "Simistarka Hadda",
    detailedGradeView: "Muuqaalka faahfaahsan ee dhammaan darajooyinka",
    noGradesFound: "Ma Jiraan Darajooyin La Helay",
    noGradesRecordedMessage: "Wali ardaygan looma diiwaan gelin wax darajooyin ah.",
    creditHours: "Saacadaha Kireedhka",
    referenceAllYears: "Tixraac Dhammaan Sanadaha",
    noStudentsFound: "Ardayna looma helin shuruudahaaga.",
    sending: "Diraya...",
    type: "Nooca",
    excellent: "Aad u Wanaagsan",
    viewPresenceRecords: "Eeg diiwaankaaga imaanshaha ee dhammaan koorsooyinka",
    noAttendanceRecords: "Lama helin diiwaan imaansho",
    noNotificationsTitle: "Ma Jiraan Ogeysiisyo",
    noNotificationsMessage: "Ma lihid wax ogeysiis ah xilligan",
    notification: "Ogeysiis",
    markAsRead: "Calaamadee in la akhriyey",
    markAllAsRead: "Calaamadee dhammaan in la akhriyey",
    deleteNotificationConfirm: "Ma hubtaa inaad rabto inaad tirtirto ogeysiiskan?",
    // Admin Link Requests
    linkRequests: "Codsiyada Xiriirka Waalid-Arday",
    linkRequestsDescription: "Ogolow ama diid codsiyada diiwaangelinta waalidka si aad ugu xirto ardayda",
    pendingRequestsTab: "Codsiyada Sugaya",
    approvedLinksTab: "Xiriirada La Ogolaaday",
    noPendingRequests: "Ma Jiraan Codsiyo Sugaya",
    pendingRequestsProcessed: "Dhammaan codsiyada xiriirka waalid-arday waa la sameeyay.",
    requestDate: "Taariikhda Codsiga",
    contactInfo: "Macluumaadka Xiriirka",
    approveSuccess: "Waalidka si guul leh ayaa loola xiriiriyay ardayga! Ogeysiis waa la diray.",
    rejectSuccess: "Codsiga xiriirka waa la diiday.",
    // Admin Announcements
    broadcastNotification: "U gudbi ogeysiis toos ah ardayda iyo waalidiinta.",
    announcementSentSuccess: "Ogeysiiska si guul leh ayaa loo diray!",
    failedToSendAnnouncement: "Waa lagu guuldareystay in la diro ogeysiiska.",
    fillTitleMessage: "Fadlan buuxi ciwaanka iyo fariinta labadaba.",
    announcementPlaceholderTitle: "Tusaale: Jadwalka Imtixaanka Waa La Sii Daayay",
    announcementPlaceholderMessage: "Ku qor ogeysiiskaaga halkan...",
    targetAudience: "Cidda Loogu Talagalay",
    everyone: "Qof kasta (Ardayda & Waalidiinta)",
    allStudents: "Dhammaan Ardayda",
    allParents: "Dhammaan Waalidiinta",
    filterByYear: "Ku Shaandhee Sannadka (Ardayda)",
    // Admin Upload
    gradeManagementPortal: "Xarunta Maamulka Darajooyinka",
    gradeManagementDescription: "Soo rar oo maamul darajooyinka ardayda. Waalidiintu waxay helaan ogeysiisyo toos ah marka darajooyinka la daabaco.",
    notificationsSent: "Ogeysiisyada La Diray",
    bulkUpload: "Soo Rarista Badan",
    selectFile: "Dooro Faylka CSV ama Excel",
    csvExcelOnly: "Faylasha CSV ama Excel kaliya",
    fileSize: "Cabirka Faylka",
    uploadProcessFile: "Soo Rar & Fuli Faylka",
    addSingleGrade: "Ku Dar Darajo Keliya",
    scoreOptional: "Buundo (Ikhtiyaari)",
    addGradeRecord: "Ku Dar Diiwaanka Darajada",
    gradeRecords: "Diiwaanada Darajada",
    publishAllPending: "Daabac Dhammaan Kuwa Sugaya",
    studentsByYear: "Ardayda Sannadkii",
    showAllGrades: "Muuji Dhammaan Darajooyinka",
    noStudentsForYear: "Ardayna looma helin sannadka la doortay.",
    notificationStatus: "Ogeysiis",
    sent: "La Diray",
    // Analytics
    noAnalyticsData: "Ma jiro xogta falanqaynta",
    ensureGradesUploaded: "Fadlan hubi in darajooyinka la soo geliyay.",
    academicAnalytics: "Falanqaynta Waxbarashada Jaamacadda",
    analyticsDescription: "Guudmar dhamaystiran oo ku saabsan waxqabadka jaamacadda, isbedelada waaxda, iyo ardayda khatarta ku jirta.",
    universityAvgGPA: "Celceliska GPA ee Jaamacadda",
    enrolledStudents: "Ardayda Diiwaangashan",
    totalGradesRecorded: "Wadarta Darajooyinka La Diiwaangeliyay",
    studentsAtRisk: "Ardayda Khatarta Ku Jirta",
    performanceByDepartment: "Waxqabadka Waax ahaan",
    avgGPA: "Celceliska GPA",
    generalGradeDistribution: "Qeybinta Darajooyinka Guud",
    atRiskStudentsTitle: "⚠️ Ardayda Khatarta Ku Jirta (GPA < 2.0 ama Darajooyin Dhicitaan)",
    studentsFlagged: "Ardayda La Calaamadeeyay",
    issue: "Arrinta",
    action: "Ficil",
    hasFailedCourses: "Wuxuu Leeyahay Koorsooyin Dhicitaan",
    lowAcademicStanding: "Heerka Waxbarasho oo Hooseeya",
    notifyParent: "Ogeysii Waalidka",
    noAtRiskStudents: "Ma jiraan arday khatar ku jirta xilligan. Shaqo wanaagsan!",
    // Reports
    academicReports: "Warbixinada Waxbarashada & Warqadaha Dhibcaha",
    reportsDescription: "Soo saar oo soo deji warbixino waxbarasho oo dhamaystiran",
    exportCSV: "Dhoofi CSV",
    print: "Daabac",
    fullTranscript: "Warqad Dhibcaha Buuxa",
    semesterReport: "Warbixinta Simistarka",
    summaryReport: "Warbixinta Kooban",
    courseGrades: "Darajooyinka Koorsooyinka",
    officialTranscript: "Warqad Dhibcaha Waxbarasho ee Rasmiga ah",
    dateGenerated: "Taariikhda La Soo Saaray",
    overallGPA: "GPA Guud",
    academicSummary: "Koobitaanka Waxbarashada",
    totalCourses: "Wadarta Koorsooyinka",
    semesters: "Simistarada",
    officialDocumentFooter: "Tani waa dukumeenti rasmi ah oo laga soo saaray Xarunta Darajooyinka Jaamacadda",
    verificationFooter: "Si aad u xaqiijiso, la xiriir maamulka jaamacadda",
    comingSoon: "Muuqaalkan dhawaan ayuu imanayaa!",
    exportedToCSV: "Warbixinta waxaa loo dhoofiyay CSV",
    // Settings
    fullNameRequired: "Magaca oo buuxa ayaa loo baahan yahay",
    emailRequired: "Iimayl ayaa loo baahan yahay",
    validEmailRequired: "Iimayl sax ah ayaa loo baahan yahay",
    phoneRequired: "Lambarka taleefanka ayaa loo baahan yahay",
    currentPasswordRequired: "Furaha hadda ayaa loo baahan yahay",
    passwordLengthRequired: "Furaha waa inuu ahaadaa ugu yaraan 6 xaraf",
    passwordsDoNotMatch: "Furayaasha isma laha",
    profileUpdatedSuccessfully: "Profaylka si guul leh ayaa loo cusbooneysiiyay",
    errorUpdatingProfile: "Khalad ayaa dhacay intii lagu jiray cusbooneysiinta profaylka",
    passwordChangedSuccessfully: "Furaha si guul leh ayaa loo beddelay",
    errorChangingPassword: "Waa la awoodi waayay in la beddelo furaha",
    saveChanges: "Keydi Isbedelada",
    // Alerts
    academicAlertsTitle: "Digniinada Waxbarashada",
    alertsDescription: "La soco waxqabadka waxbarasho ee ilmahaaga",
    alertMarkedAsRead: "Digniinta waa la akhriyay",
    errorMarkingAlert: "Khalad ayaa dhacay akhrinta digniinta",
    allAlertsMarkedAsRead: "Dhammaan digniinada waa la akhriyay",
    errorMarkingAllAlerts: "Khalad ayaa dhacay akhrinta digniinada",
    allAlerts: "Dhammaan Digniinada",
    unread: "Aan la Akhrin",
    critical: "Adag",
    highPriority: "Mudnaanta Sare",
    noAlerts: "Ma jiraan Digniino",
    allAlertsRead: "Dhammaan digniinada waa la akhriyay",
    noCriticalAlerts: "Ma jiraan digniino adag",
    noAlertsToDisplay: "Ma jiraan digniino la soo bandhigo",
    courseLabel: "Koorso",
    newBadge: "CUSUB",
    // Link Student
    linkAnotherStudent: "Ku Xir Arday Kale",
    linkStudentDescription: "Ku dar ilmo kale akoonkaaga si aad ula socoto horumarkooda.",
    verifyStudentIdFirst: "Fadlan marka hore xaqiiji aqoonsiga ardayga.",
    linkRequestSent: "Codsiga xiriirinta si guul leh ayaa loo diray! Sugitaanka ogolaansaha maamulka.",
    linkRequestFailed: "Waa la awoodi waayay in la sameeyo codsiga xiriirinta.",
    linkRequestError: "Khalad ayaa dhacay intii la diri lahaa codsiga.",
    enterStudentId: "Geli Aqoonsiga Ardayga (tusaale, S12345)",
    studentVerified: "Ardayga waa la xaqiijiyay!",
    submitting: "Gudbinaya...",
    requestLink: "Codso Xiriirin",
    linkAlreadyExists: "Aqoonsigan ardayga mar hore ayuu ku xiran yahay akoon qoys. Hal akoon oo waalid oo kaliya ayaa lagu xiri karaa ardayga.",
    studentIdNotFound: "Aqoonsiga ardayga lama helin.",
    errorVerifyingStudent: "Khalad ayaa dhacay xaqiijinta aqoonsiga ardayga.",
    // Registration Hints
    passwordRequirements: "Furaha waa inuu ku jiraa ugu yaraan 1 xaraf, 1 lambar, iyo 1 calaamad gaar ah.",
    emailSavePrompt: "Iimaylkaaga gelitaanka: {email} \n\nFadlan keydi iimaylkan si aad mustaqbalka u gasho!",
    emailUniqueHint: "Waa inuu noqdaa mid gaar ah haddii la bixiyo. Ka tag faaruq si toos ah loogu abuuro.",
    passwordHint: "Waa inuu ku jiraa ugu yaraan 1 xaraf, 1 lambar, 1 calaamad gaar ah (@$!%*#?&), ugu yaraan 6 xaraf.",
    phoneHint: "Waa inuu noqdaa mid gaar ah. Waxaa loo isticmaalaa cusbooneysiinta xaaladda SMS.",
    studentIdHint: "Geli aqoonsigaaga ardayga jaamacadda ee rasmiga ah (tusaale, UGR/1234/14).",
    fullNameHint: "Geli magacaaga oo buuxa sida uu ugu qoran yahay dukumeentiyada rasmiga ah.",
    emailHint: "Geli cinwaan iimayl sax ah (tusaale, student@university.edu).",
    confirmPasswordHint: "Dib u geli isla furaha sare si aad u xaqiijiso.",
    phoneFormatHint: "Geli lambar taleefan sax ah (tusaale, +251-911-234-567).",
    // Grade Details
    gradeDetailsTitle: "Faahfaahinta Darajada",
    gradeNotFound: "Darajada Lama Helin",
    gradeNotFoundMessage: "Darajada la codsaday lama helin.",
    goBack: "Dib u Noqo",
    studentInformation: "Macluumaadka Ardayga",
    studentName: "Magaca Ardayga",
    letterGrade: "Xarafka Darajada",
    scoreLabel: "Dhibcaha",
    gradePoint: "Dhibcaha Darajada",
    performanceScore: "Dhibcaha Waxqabadka",
    uploadedDate: "Taariikhda La Soo Geliyay",
    uploadedBy: "Waxaa Soo Geliyay",
    parentsNotified: "Waalidiinta Waa La Ogeysiiyay",
    yes: "Haa",
    no: "Maya",
    performanceEvaluation: "Qiimaynta Waxqabadka",
    percentage: "Boqolkiiba",
    scoreRatio: "Saamiga Dhibcaha",
    gpaContribution: "Kaalinta GPA",
    printReport: "Daabac Warbixinta",
    backToGrades: "Ku Noqo Darajooyinka",
    // Attendance Management
    attendanceManagementTitle: "Maamulka Xaadirka",
    selectStudent: "Dooro Arday",
    recordAttendance: "Diiwaangeli Xaadirka",
    attendanceRecordedSuccess: "Xaadirka si guul leh ayaa loo diiwaangeliyay!",
    errorRecordingAttendance: "Khalad ayaa dhacay diiwaangelinta xaadirka",
    pleaseEnterAllFields: "Fadlan geli dhammaan meelaha loo baahan yahay",
    loginFailedMessage: "Gelinta kuma guulaystay. Fadlan hubi xogtaada ee aad gelinaysid.",
    universityGradePortal: "Portal-ka Qaabka Waxbarada",
    transparentAcademicMonitoring: "Raadinta saxaafinta waxbarada oo leh rukunka sida caafimaad",
    selectYourRole: "Dooro Rool-kaaga",
    adminLogin: "Gelinta Maamulka",
    viewGradesAndAcademicProgress: "Eeg Qiimayada iyo Siiyada Waxbarashada",
    monitorChildAcademicPerformance: "Daawo Adeegsuusha Waxbarada Wiilkaaga",
    uploadAndManageStudentGrades: "Soo rar oo maamul darajooyinka ardayda",
    teacherLogin: "Gelitaanka Macallinka",
    uploadGradesByYearAndSemester: "Soo rar darajooyinka sannad iyo samiistar ahaan",
    recentUploads: "Soo Raristii Ugu Dambeeyay",
    adminReviewRequired: "Dib-u-eegis Maamul Ayay U Baahan Tahay",
    academicYear: "Sannad Waxbarasho",
    demo: "Tijaabada",
    loginAs: "Geliso Sida",
    demoApplication: "Tijaabada Codsi",
    demoApplicationDescription: "Kan soo gudbiyaa inaad si aqoonta u helaato qiimayada waxbaradaada karaa murtaa'aa. Geli xogtaada kana guji gelitaanka.",
    newUserRegisterFirst: "Isticmaalaha cusub? Hore ugu dhis",
    registerAsStudent: "Soo Dhigo Sida Baraawga",
    enterYourEmail: "Geli Imeelkaaga",
    enterYourPassword: "Geli Furehaaga",
    agreeToTermsRequired: "Waa inaad su`aan inaad xaqiijiso",
    studentAlreadyExists: "Baraawgii hore ayaa ku jira lambar ama imelkaan",
    studentRegistrationSuccess: "Soo dhowga baraawga waa la guulaystay! Waxaad galitaanka saabsan hadda.",
    studentRegistration: "Soo Dhogga Baraawga",
    registerAsStudentToAccessPortal: "Soo dhig si aad portal-ka baraawgaada saxiixdo",
    fullNamePlaceholder: "Abebe Kebede",
    studentIdPlaceholder: "UGR/1234/14",
    emailPlaceholder: "baraawga@tusaale.com",
    passwordPlaceholder: "Yaraa 6 xaraf",
    confirmPasswordPlaceholder: "Sicir furehaaga",
    phonePlaceholder: "+251 911 223344",
    selectDepartment: "Dooro Qeybta",
    year1: "Sannad 1",
    year2: "Sannad 2",
    year3: "Sannad 3",
    year4: "Sannad 4",
    year5: "Sannad 5",
    agreeToShareAcademicInfo: "Waxaan su`aan inaan waxbarashada ku wadaagid waynaha la xiriirtay oo aan helo warbixinno saxiixa waxbarashada",
    alreadyHaveAccount: "Horeyba wax kaa jira?",
    loginHere: "Geliso Halkan",
    parents: "Waynaha:",
    electricalEngineering: "Hanti Elektrik",
    mechanicalEngineering: "Hanti Miyekaanik",
    civilEngineering: "Hanti Sibili",
    medicine: "Tib",
    businessAdministration: "Maamul Dalka",
    law: "Sharciga",
    agriculture: "Faydaha",
    father: "Abaa",
    mother: "Hama",
    guardian: "Hundee",
    otherRelative: "Kan biraa",
    parentRegistration: "Galmeessi Walgituu",
    registerAsParentToMonitorAcademicProgress: "Dursa barattuu daa'imaa kee hundaarsuuf walgii ta'ii galmeessi",
    yourFullName: "Maqaa Waliigalaa Keessan",
    yourEmailOptional: "Imeelii Keessan (Gumaachisaa)",
    verify: "Mirkaneessi",
    relationshipToStudent: "Barataa Irratti",
    parentConfirmationMessage: "Barataan armaan olii walgii/hojii irraa eessuudhaan hubachiisaan isaanii fi hubachiisa dursa barattuu isaa irratti argachuu dhiyeessaa jira",
    parentRegistrationSuccessWithEmail: "Galmeessi walgii xumurameera! Maamichi dhiyeessaa jira. Dhiyeessaa booda imelii ykn SMS natti argata.",
    parentRegistrationSuccessWithoutEmail: "Galmeessi walgii xumurameera! Maamichi dhiyeessaa jira. Dhiyeessaa booda SMS hubachiisa argata.",
    parentAlreadyRegistered: "Barataa kanaaf walgii horee jira",
    studentNotFoundMessage: "Barataan hin jiru. Barataan dura duree galmeessuu qaba.",
    validEmailRequiredOrLeaveEmpty: "Imeelii dhugaa galchi ykn bakka banaa jira",
    students: "Barattoota:",
    messageToParent: "Fariin loogu talagalay hooyga",
    notificationTitle: "Cinwaanka Ogaysiiska",
    actionIssueDescription: "Sharaxaad ficilka/arrinta",
    sendNotification: "Dir Ogaysiiska",
    directChat: 'Sheeko Toos ah',
    nationalId: 'Aqoonsiga Qaranka (Fayda)',
    scanQRToRegister: 'Scan QR si aad isu diiwaangeliso',
    quickRegistration: 'Diiwaangelinta Degdega ah',
    idVerified: 'Aqoonsiga waa la xaqiijiyay',
    idPending: 'Aqoonsiga Sugaya Xaqiijinta',
    notificationSentSuccessfully: "Ogeysiis si guul leh loo soo diray!",
    studentIssueReport: "Warbixinta arrinta xarunta",
    administrativeAction: "Ficil maamul",
    regulationProblem: "Dhibaatada Xeerka",
    unregulatedAction: "Ficil aan nidaamsanayn/dhibaatada",
    notLinkedToParent: "Kuma xirna hooy",
    linkedToParent: "Waxaa ku xiran hooyga ({name})",
    searchByIdOrName: "Ku raadi Lambarka Xarunta ama Magaca...",
    attendance: "Xaadirka",
    attendanceRate: "Heerka Xaadirka",
    attendanceHistory: "Taariikhda Xaadirka",
    totalSessions: "Wadarta Kulamada",
    present: "Jooga",
    absent: "Ma Joogo",
    late: "Wuu Soo Daahay",
    excused: "Waa Loo Cudur Daaray",
    remarks: "Faallo",
    date: "Taariikhda",
    viewMyGrades: "Eeg Darajooyinkayga",
    viewChildGrades: "Eeg Darajooyinka Ilmaha",
    linkNewStudent: "Ku Xir Arday Cusub",
    sendAnnouncement: "Dir Ogeysiis",
    manageLinkRequests: "Maamul Codsiyada Xiriirka",
    uploadGrades: "Soo Geli Darajooyinka",
    attendanceRecord: "Diiwaanka Xaadirka",
    quickActions: "Tallaabooyinka Degdega ah",
    loadingDashboard: "Laga soo shubayaa daashboorka...",
    loading: "Soo shubaya...",
    myAttendance: "Xaadirkayga",
    gradesWillAppearHere: "Darajooyinku halkan ayay ka soo muuqan doonaan marka la soo geliyo.",
    noNotifications: "Ma jiraan wax ogeysiisyo ah xilligan.",
    viewAnalytics: "Eeg Falanqaynta",
    manageAttendance: "Maamul Xaadirka",
    selectAll: "Dooro Dhammaan",
    deselectAll: "Ka Noqo Dhammaan",
    remove: "Ka Saar",
    selected: "La Doortay",
    confirmRemoveSelected: "Ka saar {count} darajooyinka la doortay muuqaлка dhow?",
    confirmRemoveAll: "Ka saar dhammaan {count} darajooyinka dhow muuqaлка?",
    successfullyRemoved: "Si guul leh ayaa looga saaray {count} darajooyinka muuqaлка dhow.",
    noGradesSelected: "Ma jiraan wax darajooyin ah oo la doortay in laga saaro.",
    failedToRemove: "Waa la awoodi waayay in laga saaro darajooyinka. Fadlan isku day mar kale.",
    lowGpaWarning: "Ogeysiis Muhiim ah: Waxqabadka waxbarasho ee ilmahaagu wuxuu ka hooseeyaa heerka jaamacadda laga rabo.",
    academicAdvisory: "La-talinta Waxbarashada",
    academicAdvisoryMessage: "Ogeysiis Muhiim ah: Diiwaankaagu wuxuu muujinayaa inaad heshay darajooyin hoose. Si aad u sii wadato waxbarashadaada jaamacadda, waa inaad ilaalisaa GPA ku filan. Fadlan xoogga saar qiimayntaada soo socota oo la tasho la-taliyahaaga waxbarashada haddii aad u baahato taageero.",
    recentGrades: "Darajooyinkii Ugu Dambeeyay",
    noRecentGrades: "Ma jiraan faahfaahin darajo oo dhow",
    // New Features
    auditLogs: "Diiwaanka Hantidhawrka",
    academicCalendar: "Kalandarka Akadeemiyada",
    courseResources: "Agabka Koorsada",
    feeManagement: "Maareynta Lacagaha",
    library: "Maktabadda",
    idCard: "Kaarka Aqoonsiga",
    gradeAppeals: "Racfaanka Fasalka",
    calendar: "Kalandarka",
    resources: "Agabka",
    fees: "Lacagaha",
    schedule: "Jadwalka",
    onlineExams: "Imtixaanada Online-ka ah",
    addAdmin: "Ku dar Maamule",
    manageRecentGrades: "Maamul darajooyinka ugu dambeeyay",
    errorLoadingDashboard: "Khalad ayaa ka dhacay soo rarista Dashboard-ka",
    retry: "Isku day mar kale",
    addAdministrator: "Ku dar Maamule",
    addNewAdministrator: "Ku dar Maamule Cusub",
    grantAdminAccess: "Sii isticmaale cusub xuquuqda maamulka",
    createAdminAccount: "Samee Koonto Maamule",
    addingAdministrator: "Maamule ayaa lagu darayo...",
    securityNote: "Xusuusin Amniga",
    adminSecurityWarning: "Maamulahan cusub wuxuu heli doonaa xuquuqda buuxa ee maaraynta ardayda, darajooyinka iyo dejinta nidaamka. Hubi inaad xuquuqda siinayso qof la oggol yahay.",
    generalAdministration: "Maamulka Guud",
    itDepartment: "Waaxda IT",
    academicRegistry: "Diiwaanka Waxbarashada",
    financeOffice: "Xafiiska Maaliyadda",
    studentAffairs: "Arrimaha Ardayda",
    adminAddedSuccess: "Maamule cusub si guul leh ayaa loo daray!",
    failedToAddAdmin: "Ku dari waayay maamulaha",
    confirmRemoveGrades: "Ka saar {count} darajooyin la doortay muuqaalka dhow?",
    confirmRemoveAllGrades: "Ka saar dhammaan darajooyinka dhow muuqaalka?",
    noGradesSelectedToRemove: "Ma jiraan darajooyin la doortay in laga saaro.",
    passwordsDoNotMatch: "Furaha sirdoonka ma isku mid aha",
    fullNamePlaceholder: "Geli magaca oo dhan",
    totalStudents: "Wadarta Ardayda",
    totalParents: "Wadarta Waalidiinta",
    totalGrades: "Wadarta Darajooyinka",
    pendingRequests: "Codsiyada Sugitaanka ah"
  },
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  // Update localStorage when language changes
  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  // Get the appropriate translation based on current language
  const t = useCallback((key) => {
    const langTranslations = translations[language] || translations.en;
    // Check if the key exists in the current language, otherwise fallback to English
    return langTranslations[key] || translations.en[key] || key;
  }, [language]);

  const value = {
    language,
    setLanguage,
    t
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};